# 04 Label Sentiment

A fixed manually labelled subset of 300 headlines, 30 from each of the ten companies, is selected and manually labelled as either `positive`, `negative` or `neutral` using the predefined sentiment classes. This is done to facilitate evaluation of classification performance of the models at a later stage. These `gold_labels` are the source of truth validated and checked manually.

A fixed random seed `2025` (also defined in the constants notebook block) makes the selection reproducible. The choice of 30 headlines for each of the ten company tickers is for the purposes of balancing and prevents firms with more GDELT coverage from dominating the evaluation.

In [162]:
from pathlib import Path

import pandas as pd
from IPython.display import display
from uk_dkcot.config import (
    GOLD_LABELS_CSV_FILE_NAME,
    HEADLINE_ID_COLUMN,
    HEADLINES_ALIGNED_PRICES_CSV_FILE_NAME,
    LABEL_GOLD_COLUMN,
    NEGATIVE_LABEL,
    NEUTRAL_LABEL,
    POSITIVE_LABEL,
    VALID_SENTIMENT_LABELS,
)

In [163]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", 200)

In [164]:
# Constants
TICKER_COLUMN = "ticker"
PUBLISHED_AT_UTC_COLUMN = "published_at_utc"
PUBLISHED_AT_LONDON_COLUMN = "published_at_london"
COMPANY_NAME_COLUMN = "company_name"
HEADLINE_TEXT_COLUMN = "headline_text"


SAMPLE_PER_COMPANY = 30
RANDOM_SEED = 2025

In [165]:
# Project-root detection supports execution from either the project root or the `pipeline` directory.
working_directory = Path.cwd()
project_root = (
    working_directory.parent
    if working_directory.name == "pipeline"
    else working_directory
)

headlines_aligned_prices_file_path = project_root / "data" / "processed" / HEADLINES_ALIGNED_PRICES_CSV_FILE_NAME
gold_labels_path = project_root / "data" / "processed" / GOLD_LABELS_CSV_FILE_NAME

print("Aligned data exists:", headlines_aligned_prices_file_path.exists())

Aligned data exists: True

In [ ]:
# Load the `headlines_aligned_prices.csv` file into a data frame
headlines_aligned_prices_df = pd.read_csv(headlines_aligned_prices_file_path)

# Define the required columns for manual sentiment labelling
required_columns = [
    HEADLINE_ID_COLUMN,
    PUBLISHED_AT_UTC_COLUMN,
    PUBLISHED_AT_LONDON_COLUMN,
    TICKER_COLUMN,
    COMPANY_NAME_COLUMN,
    HEADLINE_TEXT_COLUMN,
]

# Check that there are no two headlines with the same ID
assert headlines_aligned_prices_df[HEADLINE_ID_COLUMN].is_unique
# Check that there are no missing values in the required columns defined above
assert not headlines_aligned_prices_df[required_columns].isna().any().any()
# Check that the aligned dataset contains all ten companies so each can contribute 30 headlines to the balanced sample
assert headlines_aligned_prices_df[TICKER_COLUMN].nunique() == 10

print(f"Available aligned headlines: {len(headlines_aligned_prices_df):,}")

Available aligned headlines: 9,001

In [167]:
# This section used Pandas to extract 30 headlines for each of the 10 company tickers and assign them to a dataframe called `sample_df`.
# The random seed defined in the constant notebook block is used here to ensure that the same headlines are chosen each time this code block is run (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.typing.DataFrameGroupBy.sample.html)
sample_df = (
    headlines_aligned_prices_df.groupby(TICKER_COLUMN, group_keys=False)
    .sample(n=SAMPLE_PER_COMPANY, random_state=RANDOM_SEED)
    .sort_values([TICKER_COLUMN, PUBLISHED_AT_UTC_COLUMN, HEADLINE_TEXT_COLUMN])
    .reset_index(drop=True)
)

# Display each row to manually investigate
display(sample_df.loc[0:29])
display(sample_df.loc[30:59])
display(sample_df.loc[60:89])
display(sample_df.loc[90:119])
display(sample_df.loc[120:149])
display(sample_df.loc[150:179])
display(sample_df.loc[180:209])
display(sample_df.loc[210:239])
display(sample_df.loc[240:269])
display(sample_df.loc[270:299])

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
0,5ede6243dbcfa061b21ac3df0436800d494f62bac455d88689a9493ed3a2f92a,2025-01-21T06:16:32+00:00,https://www.tmcnet.com/usubmit/2025/01/21/10133722.htm,AZN.L,AstraZeneca plc,Trinasolar Powers AstraZeneca's Sustainability Vision with Cutting-Edge Solar Carpark Rooftop Install,2025-01-21 06:16:32+00:00,2025-01-21,2025-01-22,11010.0
1,3d7dfe781decf4fc0114ae2198c293fd56e90d7676b91e46f7e444872358920d,2025-01-21T07:31:45+00:00,https://www.taiwannews.com.tw/news/6020090,AZN.L,AstraZeneca plc,Trinasolar Powers AstraZeneca's Sustainability Vision with Cutting-Edge Solar Carpark Rooftop Install | Taiwan News,2025-01-21 07:31:45+00:00,2025-01-21,2025-01-22,11010.0
2,5fe27a5b2aed7baf82841ba8630de456922c1667363ee4b2ea7887bf3ed56052,2025-01-22T13:47:57+00:00,https://www.pharmiweb.com/press-release/2025-01-22/astrazeneca-receives-two-positive-nice-recommendations-for-lung-cancer-patients-across-england-and-wales,AZN.L,AstraZeneca plc,ASTRAZENECA RECEIVES TWO POSITIVE NICE RECOMMENDATIONS FOR LUNG CANCER PATIENTS ACROSS ENGLAND AND WALES,2025-01-22 13:47:57+00:00,2025-01-22,2025-01-23,11098.0
3,56043810e5296999170979275395f9d41861a4f5ae08c5787cf4a4879254928d,2025-02-01T19:32:28+00:00,https://www.thetimes.com/business-money/companies/article/astrazeneca-accused-of-rowing-back-on-pledges-in-vaccine-hub-row-cbqqpp2nx,AZN.L,AstraZeneca plc,AstraZeneca accused of rowing back on pledges in vaccine hub row,2025-02-01 19:32:28+00:00,2025-02-01,2025-02-03,11248.0
4,f9306acc0e15bdb3ff36576665abac854f1f09f1049f29f66441bcb49355e4f3,2025-02-01T20:16:32+00:00,https://www.dailymail.co.uk/news/article-14350315/Covid-Labour-AstraZeneca-vaccine-site.html,AZN.L,AstraZeneca plc,Covid chief attacks Labour after AstraZeneca axes its plan for £450million vaccine site,2025-02-01 20:16:32+00:00,2025-02-01,2025-02-03,11248.0
5,fcc82d6727811d6febc593fe541aec14cf58a58d52fe57192cfa4948fbb9c367,2025-02-05T19:16:38+00:00,https://www.proactiveinvestors.co.uk/companies/news/1065745/bank-of-england-astrazeneca-watches-of-switzerland-thursday-ahead-1065745.html,AZN.L,AstraZeneca plc,"Bank of England, AstraZeneca, Watches of Switzerland: Thursday ahead",2025-02-05 19:16:38+00:00,2025-02-05,2025-02-06,11364.0
6,d086b67e130c1db546f9a0d5a499cfe5cec1917b93e169da4896e26d834a30d1,2025-02-06T10:47:45+00:00,https://londonlovesbusiness.com/astrazeneca-a-strong-pipeline-is-a-big-tailwind/,AZN.L,AstraZeneca plc,AstraZeneca: A strong pipeline is a big tailwind - London Business News,2025-02-06 10:47:45+00:00,2025-02-06,2025-02-07,11600.0
7,588cd1d7e976b65aa13b64cc65548175cfca8f9847ce34e4c9b99278174f9e78,2025-02-18T20:02:26+00:00,https://www.pr-inside.com/investors-in-astrazeneca-plc-should-contact-levi-korsinsky-before-r5072702.htm,AZN.L,AstraZeneca plc,Investors in AstraZeneca PLC Should Contact Levi & Korsinsky Before ...,2025-02-18 20:02:26+00:00,2025-02-18,2025-02-19,11808.0
8,dd8c3b0c4889c9c5b28a5fcb5ddead5c1c4a6ac9961e75dafee043cfb9cc29fc,2025-02-20T13:32:27+00:00,https://www.insidermonkey.com/blog/heres-why-astrazeneca-plc-azn-traded-lower-in-q4-1458054/,AZN.L,AstraZeneca plc,Here's Why AstraZeneca PLC (AZN) Traded Lower in Q4,2025-02-20 13:32:27+00:00,2025-02-20,2025-02-21,11552.0
9,0f2629ce1fe71ad89ef8aed28bb4b44ab6fcbf88c78331639d79247af69dc1f3,2025-03-03T12:48:02+00:00,https://www.thehindubusinessline.com/companies/astrazeneca-pharma-india-gets-cdsco-approval-to-import-sell-cancer-treatment-medicine/article69285132.ece,AZN.L,AstraZeneca plc,"AstraZeneca Pharma India gets CDSCO approval to import, sell cancer treatment medicine",2025-03-03 12:48:02+00:00,2025-03-03,2025-03-04,11916.0
10,da935bcc79e0457de12ca33949b4eb61ace5de3af462368cfcea03fea0c1e6d0,2025-03-12T10:17:05+00:00,https://www.tickerreport.com/banking-finance/12871077/davis-r-m-inc-invests-268000-in-astrazeneca-plc-nasdaqazn.html,AZN.L,AstraZeneca plc,"Davis R M Inc. Invests $268,000 in AstraZeneca PLC (NASDAQ:AZN)",2025-03-12 10:17:05+00:00,2025-03-12,2025-03-13,11706.0
11,3483a02b4e44bd00289582b91052d8afc6cf5340c2d8bab59709cce7fc0acbca,2025-03-28T11:02:28+00:00,https://www.tickerreport.com/banking-finance/12892601/tiaa-trust-national-association-trims-stake-in-astrazeneca-plc-nasdaqazn.html,AZN.L,AstraZeneca plc,TIAA Trust National Association Trims Stake in AstraZeneca PLC (NASDAQ:AZN),2025-03-28 11:02:28+00:00,2025-03-28,2025-03-31,11332.0
12,459a8c72d91445deadb5e60ee8468ed5957223faef08147597467a977eb0e58c,2025-04-19T06:16:43+00:00,https://www.defenseworld.net/2025/04/19/rep-bruce-westerman-buys-astrazeneca-plc-nasdaqazn-stock.html,AZN.L,AstraZeneca plc,Rep. Bruce Westerman Buys AstraZeneca PLC (NASDAQ:AZN) Stock,2025-04-19 07:16:43+01:00,2025-04-19,2025-04-22,10122.0
13,cb0bad8410453f6ec8830f3350cdfe117199bc2bdea884d78d13bc4ce3a016fd,2025-04-25T19:46:58+00:00,https://www.proactiveinvestors.co.uk/companies/news/1070158/astrazeneca-shell-lloyds-and-other-uk-banks-plus-apple-microsoft-and-meta-the-week-ahead-1070158.html,AZN.L,AstraZeneca plc,"AstraZeneca, Shell, Lloyds and other UK banks, plus Apple, Microsoft and Meta - the week ahead",2025-04-25 20:46:58+01:00,2025-04-25,2025-04-28,10416.0
14,dfe0cd47beeb4b357cb71e589eb2aa46ad5edeab7e503e463e2c40d8f1a059a1,2025-05-06T12:32:40+00:00,https://www.dailypolitical.com/2025/05/06/bamco-inc-ny-sells-25592-shares-of-astrazeneca-plc-nasdaqazn.html,AZN.L,AstraZeneca plc,"Bamco Inc. NY Sells 25,592 Shares of AstraZeneca PLC (NASDAQ:AZN)",2025-05-06 13:32:40+01:00,2025-05-06,2025-05-07,10478.0
15,2b7190abdc75341ece6c27f6fa48f8e95bd212ff069dd82e9d18d74c23d47896,2025-05-12T12:32:18+00:00,https://www.fool.co.uk/2025/05/12/why-did-the-astrazeneca-share-price-just-fall-and-what-should-we-do/,AZN.L,AstraZeneca plc,"Why did the AstraZeneca share price just fall, and what should we do?",2025-05-12 13:32:18+01:00,2025-05-12,2025-05-13,10354.0
16,ff14e42831bf0b1f957cd4251992357fcba0dc471b6b09c51b3ef3625fd285ae,2025-05-17T03:46:17+00:00,https://www.thesierraleonetelegraph.com/oxford-astrazeneca-vaccine-gives-hope-to-millions-of-africans/,AZN.L,AstraZeneca plc,Oxford AstraZeneca vaccine gives hope to millions of Africans,2025-05-17 04:46:17+01:00,2025-05-17,2025-05-19,10324.0
17,e60d8a4166f334c3a399297044557eb1410014402454a4ed35a92400159eb838,2025-06-03T10:32:40+00:00,http://www.bignewsnetwork.com/news/278255178/m42-astrazeneca-sophia-genetics-to-transform-cancer-diagnosis-care,AZN.L,AstraZeneca plc,"M42, AstraZeneca, SOPHiA GENETICS to transform cancer diagnosis, care",2025-06-03 11:32:40+01:00,2025-06-03,2025-06-04,10720.0
18,72fe5d8242ac5bb90408ff48dbf79a2806da58de26542f2504d00b7361585b01,2025-06-06T09:31:40+00:00,https://www.marketscreener.com/quote/stock/ASTRAZENECA-PLC-4000930/news/AstraZeneca-plc-Announces-Fixed-Term-Calquence-Based-Regimens-Approved-in-EU-for-Patients-with-Chro-50176875/,AZN.L,AstraZeneca plc,AstraZeneca plc Announces Fixed-Term Calquence -Based Regimens Approved in EU for Patients with Chronic Lymphocytic Leukaemia in the 1st-Line Setting AMPLIFY Phase III,2025-06-06 10:31:40+01:00,2025-06-06,2025-06-09,10788.0
19,80ea2389c470e9b03df6d52cfa95a1b9dddcca2f7d286fd27f40412b330c1aa9,2025-06-09T14:01:48+00:00,https://www.mobihealthnews.com/news/exclusive-pangaea-data-astrazenecas-alexion-partner-spot-rare-disease-ehrs,AZN.L,AstraZeneca plc,"Exclusive: Pangaea Data, AstraZeneca's Alexion partner to spot rare disease with EHRs",2025-06-09 15:01:48+01:00,2025-06-09,2025-06-10,10812.0
20,c4510cb331ff259b771a8d22d565bcce08120fe16490634121dd9264e6e11cef,2025-09-29T14:02:04+00:00,https://www.proactiveinvestors.com/companies/news/1079341/astrazeneca-s-new-york-listing-tweak-dubbed-a-knock-back-for-london-1079341.html,AZN.L,AstraZeneca plc,AstraZeneca's New York listing tweak dubbed a 'knock-back for London',2025-09-29 15:02:04+01:00,2025-09-29,2025-09-30,11034.0
21,5a80751ac5cfb8d3c175f49337db78e0d170f601479507c57e4dbdcdf071d9e1,2025-10-08T14:32:29+00:00,https://www.tickerreport.com/banking-finance/13186611/abel-hall-llc-sells-795-shares-of-astrazeneca-plc-azn.html,AZN.L,AstraZeneca plc,Abel Hall LLC Sells 795 Shares of AstraZeneca PLC $AZN,2025-10-08 15:32:29+01:00,2025-10-08,2025-10-09,12744.0
22,39d0f6c9dc04478427941a13bdbdec6a0c558f3b74665c64e22d67e82832946a,2025-10-11T16:47:11+00:00,https://pjmedia.com/david-manney/2025/10/11/trumps-leverage-pays-off-astrazeneca-signs-historic-price-deal-n4944732,AZN.L,AstraZeneca plc,Trump's Leverage Pays Off: AstraZeneca Signs Historic Price Deal – PJ Media,2025-10-11 17:47:11+01:00,2025-10-11,2025-10-13,12830.0
23,2bce3a4efb442a2427feb76ad019813596190aeab11d5ae38725a84c6880e1b5,2025-10-11T21:31:58+00:00,https://www.centralchronicle.com/trump-announces-usd-50-billion-astrazeneca-investment-to-boost-us-drug-manufacturing/,AZN.L,AstraZeneca plc,Trump announces USD 50 billion AstraZeneca investment to boost US drug manufacturing | Central India's Premier English Daily,2025-10-11 22:31:58+01:00,2025-10-11,2025-10-13,12830.0
24,91c0a75542d17ea4745368fe4bab6684c2c02af3978db42bcb30a6318cf542a2,2025-10-16T08:01:46+00:00,https://www.proactiveinvestors.com/companies/news/1080479/astrazeneca-downgraded-by-leading-investment-bank-here-s-why-1080479.html,AZN.L,AstraZeneca plc,AstraZeneca downgraded by leading investment bank. Here's why,2025-10-16 09:01:46+01:00,2025-10-16,2025-10-17,12522.0
25,eea4ca8339eb327e96f37fe0042f5a13ad0c6e0ab6a7d4de1000960f6b97c3bd,2025-10-17T17:32:27+00:00,https://www.marketscreener.com/news/astrazeneca-imfinzi-reduces-risk-of-recurrence-in-bladder-cancer-ce7d5addda8cfe22,AZN.L,AstraZeneca plc,AstraZeneca: Imfinzi reduces risk of recurrence in bladder cancer,2025-10-17 18:32:27+01:00,2025-10-17,2025-10-20,12668.0
26,5c1ff9fabfa49ebc8e6b05ffd2c373494f897785ace3a3175a32a1cac64030f2,2025-11-06T12:17:03+00:00,https://www.finanznachrichten.de/nachrichten-2025-11/66905759-astrazeneca-s-9m-and-q3-2025-financial-results-004.htm,AZN.L,AstraZeneca plc,AstraZeneca's 9M and Q3 2025 Financial Results,2025-11-06 12:17:03+00:00,2025-11-06,2025-11-07,12788.0
27,39a620f9745b0c9d02ad412fd8e26dab5fb3c5b42a748bb77a5d36397195453b,2025-11-06T13:02:27+00:00,https://timesofindia.indiatimes.com/business/international-business/pharma-growth-astrazeneca-profit-surges-77-to-2-53-bn-in-q3-us-expansion-and-cancer-drugs-power-strong-results/articleshow/125134499.cms,AZN.L,AstraZeneca plc,Pharma growth: AstraZeneca profit surges 77% to $2.53 bn in Q3; US expansion and cancer drugs power strong results,2025-11-06 13:02:27+00:00,2025-11-06,2025-11-07,12788.0
28,dd2a00a942a521973d019f052916cf640a4d96d39df0a2e44bf4976eaf7afaa0,2025-11-07T18:16:55+00:00,https://www.independent.co.uk/asia/china/china-daily/astrazeneca-investment-biotech-research-pharmaceuticals-b2857358.html,AZN.L,AstraZeneca plc,AstraZeneca to invest further in China,2025-11-07 18:16:55+00:00,2025-11-07,2025-11-10,12904.0
29,d5ba97c926b5a7d64338dbac0f2abafb6e9e73584d4278860892ac927970aa23,2025-12-11T13:03:02+00:00,https://www.dailypolitical.com/2025/12/11/oconnor-a-distinct-business-unit-of-ubs-asset-management-americas-llc-acquires-36387-shares-of-astrazeneca-plc-azn.html,AZN.L,AstraZeneca plc,"OCONNOR A Distinct Business Unit of UBS ASSET MANAGEMENT AMERICAS LLC Acquires 36,387 Shares of AstraZeneca PLC $AZN",2025-12-11 13:03:02+00:00,2025-12-11,2025-12-12,13502.0

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
30,2d5c0988ffa9af264c0f4a8be4a98d5220db20ca77f501b8f4f5ff1408ba05af,2025-01-05T09:02:10+00:00,https://www.radiokorea.com:443/community/jobs_ads_view.php?id=12475,GSK.L,GSK plc,GSK LLP CPA office - Accountant,2025-01-05 09:02:10+00:00,2025-01-05,2025-01-06,1339.0
31,ae29e55d008ce23da7bc321ee2d2091250886b3154b92ebaad065cefc943cd86,2025-01-16T21:32:09+00:00,https://www.insidermonkey.com/blog/is-gsk-plc-gsk-one-of-the-cheapest-stocks-with-biggest-upside-potential-1425371/,GSK.L,GSK plc,Is GSK plc (GSK) One of the Cheapest Stocks with Biggest Upside Potential?,2025-01-16 21:32:09+00:00,2025-01-16,2025-01-17,1366.0
32,c3661f41735019b55cb6f406ec8bf4bafe9c6c38f1cb5e58fa2a85d4325e905d,2025-01-17T09:17:21+00:00,https://eturbonews.com/antiviral-drugs-market-key-developments-value-chain-study-and-current-growth-statusgilead-sciences-hoffmann-la-roche-ag-glaxosmithkline-plc/,GSK.L,GSK plc,"Antiviral Drugs Market Key Developments, Value Chain Study and Current Growth Status|Gilead Sciences, Hoffmann-La Roche AG, GlaxoSmithKline plc",2025-01-17 09:17:21+00:00,2025-01-17,2025-01-20,1356.5
33,a526561705273feee4537835e5a28425cfae0738d576c46037b306f0ff6399b6,2025-01-21T18:32:09+00:00,https://www.fiercepharma.com/pharma/fierce-pharma-regulatory-tracker-2025,GSK.L,GSK plc,"Regulatory tracker: Cancer drugs from J&J, GSK pick up new approvals in Europe",2025-01-21 18:32:09+00:00,2025-01-21,2025-01-22,1359.0
34,cf033ccc1840657e1c097afde070543733c98c2def7124392826f6580da4901d,2025-02-01T13:46:21+00:00,https://www.modernreaders.com/news/2025/02/01/kgl-capital-management-llc-reduces-stock-holdings-in-gsk-plc-nysegsk.html,GSK.L,GSK plc,KG&L Capital Management LLC Reduces Stock Holdings in GSK plc (NYSE:GSK),2025-02-01 13:46:21+00:00,2025-02-01,2025-02-03,1400.5
35,f53e871b66618796d23b712496038e7446718eb1e5a02946bd5392da201f9783,2025-02-05T14:32:27+00:00,https://www.proactiveinvestors.co.uk/companies/news/1065662/ftse-100-live-gsk-leads-index-higher-gold-smashes-record-on-trump-trade-spat-1065662.html,GSK.L,GSK plc,FTSE 100 Live: GSK leads index higher; Gold smashes record on Trump trade spat,2025-02-05 14:32:27+00:00,2025-02-05,2025-02-06,1500.0
36,6665ee9c9a230489aec6c70b3086333ef1a8f97018e50f23afb59fd33a14366d,2025-02-05T19:16:53+00:00,https://www.proactiveinvestors.co.uk/companies/news/1065662/ftse-100-led-higher-by-gsk-gold-trounces-record-on-trump-trade-spat-1065662.html,GSK.L,GSK plc,FTSE 100 led higher by GSK; Gold trounces record on Trump trade spat,2025-02-05 19:16:53+00:00,2025-02-05,2025-02-06,1500.0
37,7e71ae05a4572cdd8ff87ea5960a36a1a4065ece968593a55ec19efa209934d0,2025-03-04T14:17:13+00:00,https://www.mckinsey.com/industries/life-sciences/our-insights/gsks-kim-branson-on-driving-innovation-with-ai-and-machine-learning,GSK.L,GSK plc,GSK's Kim Branson on driving innovation with AI and machine learning,2025-03-04 14:17:13+00:00,2025-03-04,2025-03-05,1487.5
38,c4fc6ad27f316e301b8c14c3568250a0e9ba67b02e87d10045cefb747c742f20,2025-03-05T16:32:18+00:00,https://lancasteronline.com/business/local_business/gsks-planned-800m-lancaster-county-investment-took-state-and-local-buy-in/article_12379f3e-f952-11ef-8194-f7fcfb83afef.html,GSK.L,GSK plc,GSK's planned $800M Lancaster County investment took state and local buy-in,2025-03-05 16:32:18+00:00,2025-03-05,2025-03-06,1482.0
39,eb2dab58afb1cd385de81914fc23a41e18702e88064b510ac5e93c9c5293453f,2025-03-07T00:47:24+00:00,https://www.pr-inside.com/rosen-top-ranked-investor-counsel-encourages-gsk-plc-investors-to-r5079546.htm,GSK.L,GSK plc,"ROSEN, TOP RANKED INVESTOR COUNSEL, Encourages GSK plc Investors to ...",2025-03-07 00:47:24+00:00,2025-03-07,2025-03-10,1529.0
40,4200962c46e3c59f5738f430ff4278331e6fc1ad4f78844e175f2f40530f9b72,2025-03-18T08:31:44+00:00,https://www.modernreaders.com/news/2025/03/18/sequoia-financial-advisors-llc-decreases-holdings-in-gsk-plc-nysegsk.html,GSK.L,GSK plc,Sequoia Financial Advisors LLC Decreases Holdings in GSK plc (NYSE:GSK),2025-03-18 08:31:44+00:00,2025-03-18,2025-03-19,1518.5
41,b57bd7b7bcf823df48fe129a2560b313b580033fc43171ae227465df61d42950,2025-03-24T05:16:38+00:00,https://www.themarketsdaily.com/2025/03/24/gsk-plc-longsk-insider-acquires-8120-40-in-stock.html,GSK.L,GSK plc,"GSK plc (LON:GSK) Insider Acquires £8,120.40 in Stock",2025-03-24 05:16:38+00:00,2025-03-24,2025-03-25,1487.5
42,984ac2bbe83ae3ca1b16b78c834dacfdb26c67fbce196f4d981978376cf1c9af,2025-03-30T13:17:13+00:00,https://www.pr-inside.com/shareholders-that-lost-money-on-gsk-plc-gsk-should-contact-levi-r5087859.htm,GSK.L,GSK plc,Shareholders that lost money on GSK plc(GSK) should contact Levi & ...,2025-03-30 14:17:13+01:00,2025-03-30,2025-03-31,1479.0
43,20735d3e1689b2c9c8bedfaaaec0c5c7dffae83ff8f7b92490a3a7f425bf8d48,2025-04-01T14:17:32+00:00,https://finance.yahoo.com/news/gsk-plc-gsk-most-undervalued-135954214.html,GSK.L,GSK plc,Is GSK plc (GSK) the Most Undervalued Healthcare Stock to Buy According to Analysts?,2025-04-01 15:17:32+01:00,2025-04-01,2025-04-02,1440.5
44,4c45d29b43218992ac4d54010065ba746bca4f4f96b7a8c595253215eb674bda,2025-04-17T11:17:22+00:00,https://www.directorstalkinterviews.com/gsk-plc-s-penmenvy-vaccine-backed-by-us-advisory-panel/4121192742,GSK.L,GSK plc,GSK Plc's Penmenvy vaccine backed by US Advisory Panel,2025-04-17 12:17:22+01:00,2025-04-17,2025-04-22,1351.0
45,2eb51ba673d4d8e7963ca99d18c9231213256bceae558238f32d30e6f791812c,2025-04-17T21:01:54+00:00,https://www.benzinga.com/general/biotech/25/04/44876132/us-advisory-panel-votes-to-expand-recommendation-for-pfizer-gsks-rsv-vaccines-for-older-adults-below-60-years,GSK.L,GSK plc,"US Advisory Panel Votes To Expand Recommendation For Pfizer, GSK's RSV Vaccines For Older Adults Below 60 Years - Moderna (NASDAQ:MRNA), GSK (NYSE:GSK), Pfizer (NYSE:PFE)",2025-04-17 22:01:54+01:00,2025-04-17,2025-04-22,1351.0
46,32dc2674c459fa966f760acf33e822106738ff5d8e2b5c7c403d7eb10eaf9339,2025-04-24T17:01:59+00:00,https://zenopa.com/news/abu-dhabi-and-gsk-forge-partnership-for-multi-omics-research/,GSK.L,GSK plc,Abu Dhabi and GSK Forge Partnership for Multi-omics Research - Life Science Industry News,2025-04-24 18:01:59+01:00,2025-04-24,2025-04-25,1394.0
47,673f95d88d12456b5d223522468c757a532e38884a0acb542a83d0e92a280a06,2025-05-19T09:32:16+00:00,https://www.marketscreener.com/quote/stock/GSK-PLC-9590199/news/GSK-Japan-gives-green-light-to-Blenrep-for-myeloma-49995227/,GSK.L,GSK plc,GSK: Japan gives green light to Blenrep for myeloma,2025-05-19 10:32:16+01:00,2025-05-19,2025-05-20,1405.5
48,b848337fe28e2a4365229d2935500df229b0b5e7482e3256cce3283a7b850276,2025-05-21T09:32:01+00:00,https://www.livemint.com/market/market-stats/stocks-glaxosmithkline-pharmaceutical-share-price-nse-bse-s0003695,GSK.L,GSK plc,"Glaxosmithkline Pharmaceutical Share Price Today 21 May 2025: Live NSE/BSE Rates, Technical Analysis and Expert Forecasts",2025-05-21 10:32:01+01:00,2025-05-21,2025-05-22,1427.0
49,f4cf4862812255b2449600d72afa8a17fcd2c0e0dd58ee4ef8f3a1acfe8a6499,2025-06-03T17:02:20+00:00,https://www.themarketsdaily.com/2025/06/03/gsk-nysegsk-shares-gap-down-time-to-sell.html,GSK.L,GSK plc,GSK (NYSE:GSK) Shares Gap Down – Time to Sell?,2025-06-03 18:02:20+01:00,2025-06-03,2025-06-04,1483.5
50,d01b4b9565b8801af7d6a6248bf4f1948435bf55d26b56f0a6ce7bf66e47ccb4,2025-06-13T03:31:43+00:00,https://www.siasat.com/bharat-biotech-to-develop-gsks-shigella-vaccine-3232486/,GSK.L,GSK plc,Bharat Biotech to develop GSK's Shigella vaccine,2025-06-13 04:31:43+01:00,2025-06-13,2025-06-16,1498.5
51,8b7073f92f0a09131d5811d327df340ef6e06135a3a7e1bf919c07c4f87d7958,2025-09-29T15:32:38+00:00,https://www.marketscreener.com/news/who-is-gsk-s-next-ceo-luke-miels-ce7d5bdad180f321,GSK.L,GSK plc,Who is GSK's next CEO Luke Miels?,2025-09-29 16:32:38+01:00,2025-09-29,2025-09-30,1528.0
52,6155cd00c97da5278f224809de89686ed84e34a2d81546b2d8e0439d6f6ae3ea,2025-09-30T13:33:00+00:00,https://www.cpbj.com/central-pa-part-of-gsk-30b-investment-in-u-s-manufacturing/,GSK.L,GSK plc,Central Pa. part of GSK $30B investment in U.S. manufacturing - Central Penn Business Journal,2025-09-30 14:33:00+01:00,2025-09-30,2025-10-01,1600.0
53,673f7cfdb76cd06374e04691f0429691bedf374107fbaca0ab84e585926d5cae,2025-09-30T15:03:17+00:00,https://pmlive.com/pharma_news/gsk-names-luke-miels-as-next-ceo/,GSK.L,GSK plc,GSK names Luke Miels as next CEO,2025-09-30 16:03:17+01:00,2025-09-30,2025-10-01,1600.0
54,f10bcb801011aa5b2efe314dabb509f509d28d9fd134da9866e2a5901f8e7bc3,2025-10-04T21:46:45+00:00,https://www.thisismoney.co.uk/money/markets/article-15161691/Outgoing-GSK-boss-Emma-Walmsley-takes-swipe-Labour.html,GSK.L,GSK plc,Outgoing GSK boss Emma Walmsley takes swipe at Labour,2025-10-04 22:46:45+01:00,2025-10-04,2025-10-06,1600.0
55,1eac781d324533fc16a4aa68bf24ae14fde46dcfb6b9ff758cec1ab9b816ea0e,2025-11-13T12:17:14+00:00,https://www.proactiveinvestors.co.uk/companies/news/1082389/ftse-100-live-stocks-slide-lower-as-shell-bp-gsk-ex-div-weigh-1082389.html,GSK.L,GSK plc,"FTSE 100 Live: Stocks slide lower as Shell, BP, GSK ex-div weigh",2025-11-13 12:17:14+00:00,2025-11-13,2025-11-14,1805.5
56,c264b3b4440c5c4e577ae6fa262056b574d425e1801b696c1cd8eab03ed82bff,2025-11-20T11:48:07+00:00,https://www.prnewswire.com/news-releases/flagship-pioneering-announces-new-agreements-with-profound-therapeutics-and-quotient-therapeutics-under-its-collaboration-with-gsk-302621224.html,GSK.L,GSK plc,Flagship Pioneering Announces New Agreements with ProFound Therapeutics and Quotient Therapeutics Under its Collaboration with GSK,2025-11-20 11:48:07+00:00,2025-11-20,2025-11-21,1756.5
57,61247c6fc04712bafc1b2ff7ce8687874682478dc03a609d4362ba18f6260e06,2025-12-19T15:48:02+00:00,https://www.benzinga.com/analyst-stock-ratings/analyst-color/25/12/49509978/gsk-deal-is-key-validation-for-camp4s-drug-discovery-platform-analyst,GSK.L,GSK plc,"GSK Deal Is Key Validation For CAMP4's Drug Discovery Platform: Analyst - Camp4 Therapeutics (NASDAQ:CAMP), GSK (NYSE:GSK)",2025-12-19 15:48:02+00:00,2025-12-19,2025-12-22,1808.5
58,5cdf9f41005e0487cc113b67b78608c7321718ea96a8c0e2c5760f18753adce5,2025-12-21T13:32:35+00:00,https://www.themarketsdaily.com/2025/12/21/gsk-plc-sponsored-adr-gsk-shares-sold-by-sound-income-strategies-llc.html,GSK.L,GSK plc,GSK PLC Sponsored ADR $GSK Shares Sold by Sound Income Strategies LLC,2025-12-21 13:32:35+00:00,2025-12-21,2025-12-22,1808.5
59,c5e7cfba7448204bc26bf1edfa43c440f263a2a7d242e655ff049f57e5d474a0,2025-12-22T10:02:29+00:00,https://www.proactiveinvestors.co.uk/companies/news/1084788/ftse-100-live-defensives-stocks-drag-index-lower-gsk-agrees-us-pricing-deal-1084788.html,GSK.L,GSK plc,"FTSE 100 Live: Defensives stocks drag index lower, GSK agrees US pricing deal",2025-12-22 10:02:29+00:00,2025-12-22,2025-12-23,1809.5

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
60,9fd1e3e42081546c50f1cd0523f10d4dd72fa3a92d5e4f22c964d272e052586b,2025-01-08T08:31:24+00:00,https://www.finanznachrichten.de/nachrichten-2025-01/64236665-halma-appoints-carole-cran-to-succeed-steve-gunning-as-cfo-020.htm,HLMA.L,Halma plc,Halma Appoints Carole Cran To Succeed Steve Gunning As CFO,2025-01-08 08:31:24+00:00,2025-01-08,2025-01-09,2693.0
61,7951e6cce3b66fea28d9f2233c1b519b0b3154ec436f5a98d6237f5a854861d1,2025-01-08T11:47:14+00:00,https://www.directorstalkinterviews.com/halma-plc-cfo-steve-gunning-to-retire-carole-cran-appointed-as-cfo-designate/4121182811,HLMA.L,Halma plc,"Halma Plc CFO Steve Gunning to retire, Carole Cran appointed as CFO Designate",2025-01-08 11:47:14+00:00,2025-01-08,2025-01-09,2693.0
62,b489378b892728166eedfbeb2361b5279b9a15329d0e339a7f32e59fb82c4edf,2025-01-10T13:47:23+00:00,https://theenterpriseleader.com/2025/01/10/halma-lonhlma-hits-new-52-week-low-time-to-sell.html,HLMA.L,Halma plc,Halma (LON:HLMA) Hits New 52-Week Low – Time to Sell?,2025-01-10 13:47:23+00:00,2025-01-10,2025-01-13,2674.0
63,0af52bb8d506f37efe7dfe3017adf87c531da09c3e4c63250ba95fcab95fe4ee,2025-01-24T16:31:44+00:00,https://www.investorschronicle.co.uk/content/f1b24fad-30cb-58b0-9617-ca0f5e2366ce,HLMA.L,Halma plc,Halma and JD Sports: Big director share deals this week,2025-01-24 16:31:44+00:00,2025-01-24,2025-01-27,2838.0
64,fd7efa6429a9c0c136b57a6cd8f492437d0bee5904639769fca419be3e1eef1b,2025-03-13T09:17:08+00:00,https://www.sharecast.com/news/news-and-announcements/halma-now-expects-full-year-operating-margin-above-21--19142795.html,HLMA.L,Halma plc,Halma now expects full-year operating margin above 21%,2025-03-13 09:17:08+00:00,2025-03-13,2025-03-14,2675.0
65,48ef3f768c893dd392e2c0ff8782de83f41a37b2d63fb4116e48d2c36a9c4f8b,2025-03-13T09:17:24+00:00,https://www.sharecast.com/news/market-live-email/cc-operating-profit-seen-modestly-below-target-halma-hails-good-progress--19143018.html,HLMA.L,Halma plc,"C&C operating profit seen modestly below target, Halma hails 'good progress'",2025-03-13 09:17:24+00:00,2025-03-13,2025-03-14,2675.0
66,ea75c5b2c0cbece513ab3ba0b3c8f0995a08a26055044917db3baa2c480a999e,2025-03-16T19:46:26+00:00,https://www.dailypolitical.com/2025/03/16/short-interest-in-halma-plc-otcmktshlmaf-declines-by-26-6.html,HLMA.L,Halma plc,Short Interest in Halma plc (OTCMKTS:HLMAF) Declines By 26.6%,2025-03-16 19:46:26+00:00,2025-03-16,2025-03-17,2712.0
67,57cb80b5490058c5cb78a3a49bd09478328af6c53d7449a5ac2e36f85904d498,2025-03-17T17:17:30+00:00,https://www.wkrb13.com/2025/03/17/halma-plc-otcmktshlmaf-short-interest-down-26-6-in-february.html,HLMA.L,Halma plc,Halma plc (OTCMKTS:HLMAF) Short Interest Down 26.6% in February,2025-03-17 17:17:30+00:00,2025-03-17,2025-03-18,2702.0
68,38ca2399cedf09ea570c80746c0dcf5c9a1c5bd1f3708636ff482b18294bfb0f,2025-06-12T06:46:29+00:00,https://www.finanznachrichten.de/nachrichten-2025-06/65644560-halma-fy25-results-climb-lifts-dividend-fy26-outlook-positive-020.htm,HLMA.L,Halma plc,"Halma FY25 Results Climb, Lifts Dividend; FY26 Outlook Positive",2025-06-12 07:46:29+01:00,2025-06-12,2025-06-13,3086.0
69,37210019842ca172aff4bca5028a13920758007bc774496b607e5645f024de24,2025-06-12T07:16:44+00:00,https://www.marketscreener.com/quote/stock/HALMA-PLC-9590130/news/Tesco-backs-outlook-Halma-hails-record-earnings-50221936/,HLMA.L,Halma plc,Tesco backs outlook; Halma hails record earnings,2025-06-12 08:16:44+01:00,2025-06-12,2025-06-13,3086.0
70,b77638bfca77949ff7b07e1d959406b17af5313c8fde83221077ac17c87de0e9,2025-06-12T09:01:44+00:00,https://www.directorstalkinterviews.com/halma-plc-reports-22nd-consecutive-year-of-record-profit/4121201774,HLMA.L,Halma plc,Halma Plc reports 22nd consecutive year of record profit,2025-06-12 10:01:44+01:00,2025-06-12,2025-06-13,3086.0
71,7f31a0753af2036ef0ce04d8ef7f7212a4bf2eec7baeeca086b6f68b627e41b3,2025-06-12T11:02:22+00:00,https://www.fool.co.uk/2025/06/12/halma-shares-surge-on-outstanding-results-but-is-there-trouble-ahead/,HLMA.L,Halma plc,Halma shares surge on outstanding results. But is there trouble ahead?,2025-06-12 12:02:22+01:00,2025-06-12,2025-06-13,3086.0
72,965721c23c8e372c566fe688b11811b3de030988b4dfd23358823619535c5ed3,2025-06-12T12:18:10+00:00,https://www.thetimes.com/business-money/companies/article/halma-delivers-profitable-growth-with-46th-year-of-rising-dividends-n53x8bt27,HLMA.L,Halma plc,Halma delivers profitable growth with 46th year of rising dividends,2025-06-12 13:18:10+01:00,2025-06-12,2025-06-13,3086.0
73,2038d0397e6a4b7d97def4a084a518baca2209a38ad2023c27638cdb293426af,2025-06-13T16:47:04+00:00,https://finance.yahoo.com/news/halma-price-target-raised-2-162513459.html,HLMA.L,Halma plc,"Halma price target raised to 2,490 GBp from 2,140 GBp at Jefferies",2025-06-13 17:47:04+01:00,2025-06-13,2025-06-16,3112.0
74,a6a75b1418a0ba36c0cce4c826b76a631d0db44bb12fe0eda96de667c91f0a02,2025-09-25T07:17:02+00:00,https://www.marketscreener.com/news/halma-lifts-guidance-petershill-proposes-de-listing-ce7d58d2df8aff2d,HLMA.L,Halma plc,Halma lifts guidance; Petershill proposes de-listing,2025-09-25 08:17:02+01:00,2025-09-25,2025-09-26,3384.0
75,0baf28a852324829e68c8639f1abbeae606ea9e2b45dedf5c539c6dba94c8e38,2025-09-25T07:47:27+00:00,https://www.proactiveinvestors.co.uk/companies/news/1079148/halma-hits-new-all-time-high-as-revenue-outlook-hiked-1079148.html,HLMA.L,Halma plc,Halma hits new all-time high as revenue outlook hiked,2025-09-25 08:47:27+01:00,2025-09-25,2025-09-26,3384.0
76,d6d76c438176cfec88eb87748410e6d98e9c0de1b25f90c5ee61084d88f05217,2025-09-25T10:02:13+00:00,https://www.proactiveinvestors.com/companies/news/1079130/ftse-100-live-london-stocks-beat-retreat-babcock-drops-but-halma-rises-1079130.html,HLMA.L,Halma plc,"FTSE 100 Live: London stocks beat retreat, Babcock drops but Halma rises",2025-09-25 11:02:13+01:00,2025-09-25,2025-09-26,3384.0
77,1d603498b50b17869e11513204fc2a802fe63d4c51d94c20c05cfbf367c5b7f7,2025-10-06T13:16:52+00:00,https://www.proactiveinvestors.co.uk/companies/news/1079753/halma-gets-a-lift-melrose-keeps-its-cool-1079753.html,HLMA.L,Halma plc,"Halma gets a lift, Melrose keeps its cool",2025-10-06 14:16:52+01:00,2025-10-06,2025-10-07,3524.0
78,340403f3558a070cd0d523bfc8e788ccfa6363ed311f2e732c649edf6e6b37da,2025-11-04T20:02:23+00:00,https://www.themarketsdaily.com/2025/11/04/halma-otcmktshlmaf-hits-new-12-month-low-whats-next.html,HLMA.L,Halma plc,Halma (OTCMKTS:HLMAF) Hits New 12-Month Low – What's Next?,2025-11-04 20:02:23+00:00,2025-11-04,2025-11-05,3532.0
79,26b49349d4b61410b8151fc2a64eea58ac4d637df4b4354b6a54a9300492ff05,2025-11-20T08:31:54+00:00,https://www.marketscreener.com/news/halma-lifts-annual-revenue-forecast-on-strong-us-data-centre-demand-ce7d5ed9d08bf726,HLMA.L,Halma plc,Halma lifts annual revenue forecast on strong US data centre demand,2025-11-20 08:31:54+00:00,2025-11-20,2025-11-21,3542.0
80,a13eb1934a13394952dfc257667583c8069ade89057202701b76644d7ef74306,2025-11-20T08:47:22+00:00,https://www.marketscreener.com/news/halma-boosts-outlook-as-delivers-record-first-half-sales-and-profit-ce7d5ed9d08af725,HLMA.L,Halma plc,Halma boosts outlook as delivers record first half sales and profit,2025-11-20 08:47:22+00:00,2025-11-20,2025-11-21,3542.0
81,b4bbef20e6f2ee83e17282c822aecf93071309e2f307cf3bec685dc546fee502,2025-11-20T15:02:40+00:00,https://www.rttnews.com/story.aspx?Id=3597200,HLMA.L,Halma plc,"FTSE Modestly Higher; Halma, Games Workshop Soar On Earnings Updates",2025-11-20 15:02:40+00:00,2025-11-20,2025-11-21,3542.0
82,b4b53b05ddc2abe1998d2724580a95484d27473ef10c122e542399b5dcabc143,2025-11-20T16:17:15+00:00,https://www.dailypolitical.com/2025/11/20/halma-otcmktshlmaf-sets-new-12-month-high-whats-next.html,HLMA.L,Halma plc,Halma (OTCMKTS:HLMAF) Sets New 12-Month High – What's Next?,2025-11-20 16:17:15+00:00,2025-11-20,2025-11-21,3542.0
83,14a23b5217a44338302c165f3beb28920463a8e2fcef20932ab83345f3483da6,2025-11-20T19:16:58+00:00,https://www.sharecast.com/news/news-and-announcements/halma-hikes-payout-on-strong-h1-growth-margin-expansion--21258877.html,HLMA.L,Halma plc,"Halma raises FY revenue guidance, hikes payout on strong H1 growth",2025-11-20 19:16:58+00:00,2025-11-20,2025-11-21,3542.0
84,4c30d0ee2f8e20fb8d2a423e0c255b11a00bee596b0201725a8cde6ef97ebe0b,2025-11-24T17:02:25+00:00,https://www.tickerreport.com/banking-finance/13264651/halma-lonhlma-price-target-raised-to-gbx-3820.html,HLMA.L,Halma plc,"Halma (LON:HLMA) Price Target Raised to GBX 3,820",2025-11-24 17:02:25+00:00,2025-11-24,2025-11-25,3566.0
85,60064160f1fddd2432d9855dd026478a4c11370dd015d4789aa3de6e9bea12ce,2025-11-28T19:32:03+00:00,https://www.dailypolitical.com/2025/11/28/halma-otcmktshlmaf-shares-down-3-5-time-to-sell.html,HLMA.L,Halma plc,Halma (OTCMKTS:HLMAF) Shares Down 3.5% – Time to Sell?,2025-11-28 19:32:03+00:00,2025-11-28,2025-12-01,3546.0
86,4681d0f2ce41dac94f4830059bf3dabcaf013d9ad8335350e69a4b38a095deaa,2025-11-29T18:16:36+00:00,https://www.themarketsdaily.com/2025/11/29/critical-survey-halma-otcmktshlmaf-versus-digital-ally-inc-nv-nasdaqdgly.html,HLMA.L,Halma plc,Critical Survey: Halma (OTCMKTS:HLMAF) versus Digital Ally Inc./NV (NASDAQ:DGLY),2025-11-29 18:16:36+00:00,2025-11-29,2025-12-01,3546.0
87,e45ac38ccaeb47feb1711615950aa13cf5e1569f5d03db4eab9a8dbd1bc2a6df,2025-12-05T08:46:57+00:00,https://www.sharecast.com/news/news-and-announcements/halma-buys-hazard-detection-firm-e2s-for-pound230m--21332944.html,HLMA.L,Halma plc,Halma buys hazard detection firm E2S for £230m,2025-12-05 08:46:57+00:00,2025-12-05,2025-12-08,3664.0
88,23bb0745af3777ff94f842291a912ec9d572697a2136c535a0147004a61799a7,2025-12-14T02:32:16+00:00,https://www.tickerreport.com/banking-finance/13291167/halma-lonhlma-shares-cross-above-200-day-moving-average-heres-what-happened.html,HLMA.L,Halma plc,Halma (LON:HLMA) Shares Cross Above 200 Day Moving Average – Here's What Happened,2025-12-14 02:32:16+00:00,2025-12-14,2025-12-15,3482.0
89,c5ce1150d810644f9bc7eaab9627e30519023ce9c723f50d9da8b497030d5f10,2025-12-18T06:47:43+00:00,https://www.tickerreport.com/banking-finance/13294880/halma-plc-lonhlma-receives-gbx-3695-average-target-price-from-analysts.html,HLMA.L,Halma plc,"Halma plc (LON:HLMA) Receives GBX 3,695 Average Target Price from Analysts",2025-12-18 06:47:43+00:00,2025-12-18,2025-12-19,3538.0

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
90,6d75ba4ff178fc153594fe8321455871c208ed7c322814c752bfe968d34e6267,2025-01-06T14:31:59+00:00,https://www.mortgagesolutions.co.uk/news/2025/01/06/hsbc-broadens-availability-of-energy-efficient-cashback/,HSBA.L,HSBC Holdings plc,HSBC broadens availability of energy-efficient cashback,2025-01-06 14:31:59+00:00,2025-01-06,2025-01-07,774.500000
91,6a5f28a64bef6cbdcae26c5f5c07dfb2080b271010f04637442a2bcde85ad00a,2025-01-09T15:47:11+00:00,https://www.rediff.com/business/report/hsbc-downgrades-indian-stock-markets-to-neutral-from-overweight-for-2025/20250109.htm,HSBA.L,HSBC Holdings plc,HSBC downgrades Indian stock markets to 'neutral' from 'overweight' for 2025,2025-01-09 15:47:11+00:00,2025-01-09,2025-01-10,800.599976
92,f2e679727d0bcdfcad3f48af62be12f1496422d5670dfbba197ea7a2e07a220b,2025-01-20T22:01:51+00:00,https://www.insidermonkey.com/blog/hsbc-holdings-plc-hsbc-why-this-mega-cap-stock-could-continue-surging-post-52-week-highs-1428182/,HSBA.L,HSBC Holdings plc,HSBC Holdings plc (HSBC): Why This Mega-cap Stock Could Continue Surging Post 52-week Highs,2025-01-20 22:01:51+00:00,2025-01-20,2025-01-21,827.299988
93,eb5adbbf3beeb61dfabb7531d6f530dfe1fe7386749ee939f1cd7fa1dfe889cc,2025-01-21T12:32:19+00:00,https://www.dailypolitical.com/2025/01/21/mitchell-pahl-private-wealth-llc-has-1-18-million-stake-in-hsbc-holdings-plc-nysehsbc.html,HSBA.L,HSBC Holdings plc,Mitchell & Pahl Private Wealth LLC Has $1.18 Million Stake in HSBC Holdings plc (NYSE:HSBC),2025-01-21 12:32:19+00:00,2025-01-21,2025-01-22,827.900024
94,654f20fbbb78cbc94f525c81fddafae954f8db3b0813b31f1016e11887dcc61f,2025-01-23T17:16:39+00:00,https://www.birminghammail.co.uk/news/cost-of-living/hsbc-warns-customers-over-service-30850912,HSBA.L,HSBC Holdings plc,HSBC warns customers over service being axed after 'careful consideration',2025-01-23 17:16:39+00:00,2025-01-23,2025-01-24,829.000000
95,ea589f113f4e7c0ed70502d9d7e83156220cca628824bd88ba059cb6ffe038b0,2025-01-28T12:02:00+00:00,https://www.kentonline.co.uk/news/national/hsbc-to-wind-down-parts-of-investment-banking-units-in-uk-europe-and-us-137904/,HSBA.L,HSBC Holdings plc,"HSBC to wind down parts of investment banking units in UK, Europe and US",2025-01-28 12:02:00+00:00,2025-01-28,2025-01-29,825.400024
96,119071e2d6a92a2f9873f640b29ac601d43de0f44f412c9588dd148a74b3d0c3,2025-02-19T08:46:55+00:00,https://www.directorstalkinterviews.com/hsbc-holdings-plc-delivers-strong-2024-performance-pbt-rose-by-2-0bn-to-32-3bn/4121186814,HSBA.L,HSBC Holdings plc,"HSBC Holdings Plc delivers strong 2024 performance, PBT rose by $2.0bn to $32.3bn",2025-02-19 08:46:55+00:00,2025-02-19,2025-02-20,888.900024
97,a5f6ab62c6282cb69cc5c9e592ba4ea260ff646286bd27b8d2e6d05e4323391a,2025-02-19T12:01:58+00:00,https://www.sharecast.com/news/news-and-announcements/hsbc-posts-better-than-expected-q4-profit-plans-2bn-of-share-buybacks--18937308.html,HSBA.L,HSBC Holdings plc,"HSBC posts better-than-expected Q4 profit, plans $2bn of share buybacks",2025-02-19 12:01:58+00:00,2025-02-19,2025-02-20,888.900024
98,6df0c492f7eacdb9d96734eb28ade4ed408db80171ff47ccee4043ad2e0e82aa,2025-03-21T08:02:03+00:00,https://www.themarketsdaily.com/2025/03/21/bayerische-motoren-werke-aktiengesellschaft-otcmktsbmwyy-downgraded-to-hold-rating-by-hsbc.html,HSBA.L,HSBC Holdings plc,"Bayerische Motoren Werke Aktiengesellschaft (OTCMKTS:BMWYY) Downgraded to ""Hold"" Rating by HSBC",2025-03-21 08:02:03+00:00,2025-03-21,2025-03-24,884.700012
99,7060d6323cefd0607cc938e336d7d4d94117105320b328d707f8eed4e8dd537f,2025-03-27T15:32:28+00:00,https://www.efinancialcareers.com/news/hsbc-zero-bonuses-fired,HSBA.L,HSBC Holdings plc,"How HSBC could cancel bonuses for everyone it fired, and the questions that remain",2025-03-27 15:32:28+00:00,2025-03-27,2025-03-28,883.099976
100,1eb4a1423b154054632b9ce96f24f0c0d5ece70486901dda823daf0232d8b88c,2025-04-29T19:17:13+00:00,https://www.benzinga.com/25/04/45079467/hsbc-q1-mixed-earnings-revenue-down-but-core-business-shows-underlying-strength-announced-buyback,HSBA.L,HSBC Holdings plc,Why Is HSBC Stock Trading Higher On Tuesday? - HSBC Holdings (NYSE:HSBC),2025-04-29 20:17:13+01:00,2025-04-29,2025-04-30,848.799988
101,08987c7294b30af3dfe47ee60b01c6ada4adb94cfa0978743df805a8f54ba504,2025-05-02T10:32:04+00:00,https://www.mortgagesolutions.co.uk/news/2025/05/02/hsbc-tsb-coventry-bs-and-principality-bs-cut-rates-round-up/,HSBA.L,HSBC Holdings plc,"HSBC, TSB, Coventry BS and Principality BS cut rates – round-up",2025-05-02 11:32:04+01:00,2025-05-02,2025-05-06,849.700012
102,15df415aa389712281c75f235fd322ba234a7e850180e8998f55849b6e2b085b,2025-05-02T20:16:53+00:00,https://www.channelnewsasia.com/business/exclusive-hsbc-asset-managements-global-head-sustainability-depart-5105856,HSBA.L,HSBC Holdings plc,Exclusive-HSBC Asset Management's global head of sustainability to depart,2025-05-02 21:16:53+01:00,2025-05-02,2025-05-06,849.700012
103,083cdfadb9b2a5774ea172e22b85a51f176edb2b44d4853521aaa73106c2dc06,2025-05-16T00:46:57+00:00,https://economictimes.indiatimes.com/industry/banking/finance/banking/india-among-hsbcs-top-4-priority-growth-markets-says-ceo-georges-elhedery/articleshow/121195590.cms,HSBA.L,HSBC Holdings plc,"India among HSBC's top 4 priority growth markets, says CEO Georges Elhedery",2025-05-16 01:46:57+01:00,2025-05-16,2025-05-19,876.200012
104,bc6cd21ee5c788110475669382edb11a888599ff1cd64db12c8a5e74256014ff,2025-05-23T09:17:39+00:00,https://economictimes.indiatimes.com/industry/renewables/hybrid-vehicles-complementing-growth-of-evs-in-india-hsbc-report/articleshow/121359656.cms,HSBA.L,HSBC Holdings plc,Hybrid vehicles complementing growth of EVs in India: HSBC report,2025-05-23 10:17:39+01:00,2025-05-23,2025-05-27,873.500000
105,c22fc1492d8a7c07429f0af1c58e4cbe535a5b93ad98573ae553b7cba1c78bc4,2025-06-06T04:31:34+00:00,https://www.marketscreener.com/quote/stock/HSBC-HOLDINGS-PLC-16896790/news/HSBC-Chair-Tucker-to-return-to-Asia-insurer-AIA-after-overseeing-bank-overhaul-50173029/,HSBA.L,HSBC Holdings plc,HSBC Chair Tucker to return to Asia insurer AIA after overseeing bank overhaul,2025-06-06 05:31:34+01:00,2025-06-06,2025-06-09,879.299988
106,a4e88da38036d32b4a931ee187983e647d391567b625026fc1deb46f7639ce8d,2025-06-07T08:01:48+00:00,https://www.themarketsdaily.com/2025/06/07/embraer-nyseerj-upgraded-at-hsbc.html,HSBA.L,HSBC Holdings plc,Embraer (NYSE:ERJ) Upgraded at HSBC,2025-06-07 09:01:48+01:00,2025-06-07,2025-06-09,879.299988
107,5d604d03e6d19264e0072f61b202fc29c81ba03bd9efb50da5c8ca4db7108377,2025-09-24T08:16:46+00:00,https://www.livemint.com/market/stock-market-news/sensex-to-hit-94-000-by-2026-end-hsbc-upgrades-india-equities-to-overweight-says-valuations-no-longer-a-concern-11758700326514.html,HSBA.L,HSBC Holdings plc,"Sensex to hit 94,000 by 2026-end? HSBC upgrades India equities to 'Overweight'; says valuations no longer a concern",2025-09-24 09:16:46+01:00,2025-09-24,2025-09-25,1024.000000
108,535fbc5a891019aecdf5b3a238704afbfe1306790a9a64b65293d3fa17621b8d,2025-10-17T10:17:13+00:00,https://www.theweek.in/news/biz-tech/2025/10/17/canara-hsbc-life-insurance-ipo-hits-the-stock-market-with-0-per-cent-listing-gains-latest-details.html,HSBA.L,HSBC Holdings plc,"Canara HSBC Life Insurance IPO hits the stock market with 0 per cent listing gains, latest details",2025-10-17 11:17:13+01:00,2025-10-17,2025-10-20,988.000000
109,399afef6cd6a206b9c170f9569eca23d744039aaeca447997864f17ff4402959,2025-10-28T09:17:18+00:00,https://www.bloomberg.com/news/articles/2025-10-28/hsbc-reviews-ties-to-hedge-funds-with-credit-fears-on-the-rise,HSBA.L,HSBC Holdings plc,HSBC Reviews Ties to Hedge Funds With Credit Fears on the Rise,2025-10-28 09:17:18+00:00,2025-10-28,2025-10-29,1057.400024
110,74fb8211cd620c648fcfbff00481b0679e0bb1f7032f722e0b2565a2f55980c0,2025-10-28T09:32:17+00:00,https://www.marketscreener.com/news/hsbc-lifts-income-outlook-though-madoff-lawsuit-charges-mar-profit-ce7d5ddfde8bf621,HSBA.L,HSBC Holdings plc,"HSBC lifts income outlook, though Madoff lawsuit charges mar profit",2025-10-28 09:32:17+00:00,2025-10-28,2025-10-29,1057.400024
111,72aa4b69683c0eb27850eb1f20bd0cdaddbb714c2fb98327d7ed8ee7bfb67205,2025-10-28T13:47:02+00:00,https://www.mortgagestrategy.co.uk/news/brokers-give-backing-to-home-sales-revolution-hsbc/,HSBA.L,HSBC Holdings plc,Brokers give backing to home sales revolution: HSBC,2025-10-28 13:47:02+00:00,2025-10-28,2025-10-29,1057.400024
112,355f1f1217cd20e1371617b27875d8d32a09b4e5c167a4f9e9ec7449df4514f4,2025-10-28T23:17:12+00:00,https://www.investorschronicle.co.uk/content/912f28f0-5af0-4bb2-b0c0-2724a9f4dae4,HSBA.L,HSBC Holdings plc,"Companies roundup: HSBC, Next 15 and RWS",2025-10-28 23:17:12+00:00,2025-10-28,2025-10-29,1057.400024
113,d5f5c98707fb1e5ca5bd4c248ac900ac207ae8c25fac237aba32025b318e25c1,2025-11-10T17:32:31+00:00,https://www.birminghammail.co.uk/news/money/tsb-hsbc-slash-mortgage-rates-32844983,HSBA.L,HSBC Holdings plc,TSB and HSBC slash mortgage rates by up to 0.1% ahead of Autumn Budget,2025-11-10 17:32:31+00:00,2025-11-10,2025-11-11,1098.800049
114,8f951a2eb0e4557654b19f1232977eed0655b5b5498ab42d57e90deb764c80e4,2025-11-12T19:32:30+00:00,https://economictimes.indiatimes.com/news/company/corporate-trends/indian-firms-among-worlds-most-optimistic-hsbc-survey-shows-stronger-demand-and-profit-outlook/articleshow/125282664.cms,HSBA.L,HSBC Holdings plc,"Indian firms among world's most optimistic, HSBC survey shows stronger demand and profit outlook",2025-11-12 19:32:30+00:00,2025-11-12,2025-11-13,1120.000000
115,22f1e39564a3fdfd5ed6dbb41ebb5f361323e403a1d9bd297642f105424c47ab,2025-11-29T00:17:03+00:00,https://island.lk/hsbc-recognised-as-sri-lankas-best-transaction-bank-for-2025-by-euromoney/,HSBA.L,HSBC Holdings plc,HSBC recognised as Sri Lanka's Best Transaction Bank for 2025 by Euromoney – The Island,2025-11-29 00:17:03+00:00,2025-11-29,2025-12-01,1074.400024
116,1f46a291b0028b745e724859535669e985906cccfeeb2f919cea0a1aa035d077,2025-11-30T14:47:09+00:00,https://www.dailypolitical.com/2025/11/30/hsbc-holdings-plc-sells-26990-shares-of-becton-dickinson-and-company-bdx.html,HSBA.L,HSBC Holdings plc,"Hsbc Holdings PLC Sells 26,990 Shares of Becton, Dickinson and Company $BDX",2025-11-30 14:47:09+00:00,2025-11-30,2025-12-01,1074.400024
117,01ac9e0ad12aac791c70612e7122282b238020e6ba0cf253193625ac815e18cd,2025-12-02T12:02:05+00:00,https://www.themarketsdaily.com/2025/12/02/aecom-acm-shares-bought-by-hsbc-holdings-plc.html,HSBA.L,HSBC Holdings plc,AECOM $ACM Shares Bought by Hsbc Holdings PLC,2025-12-02 12:02:05+00:00,2025-12-02,2025-12-03,1082.199951
118,f070d60f481899f5b6112c23e8d47b501fc35fccd984270a64e38d4c02e6756e,2025-12-03T09:17:19+00:00,https://www.sharecast.com/news/market-live-email/market-live--21318796.html,HSBA.L,HSBC Holdings plc,"HSBC taps former KPMG partner for chairman, Spire Healthcare FY earnings seen at bottom end of guidance",2025-12-03 09:17:19+00:00,2025-12-03,2025-12-04,1076.199951
119,459ad030aa6ebeaf83aac5d5293fceffed23cdd660ffa3fc60f9ff6ae9bd87a0,2025-12-11T09:02:09+00:00,https://www.insidermonkey.com/blog/hsbc-upgrades-abbvie-abbv-to-buy-raises-price-target-to-265-1658142/,HSBA.L,HSBC Holdings plc,"HSBC Upgrades AbbVie (ABBV) to Buy, Raises Price Target to $265",2025-12-11 09:02:09+00:00,2025-12-11,2025-12-12,1128.199951

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
120,928063a2634fa644a0e69b36c8f877da351ab21ed9ec01241e320928ed8b2e8d,2025-01-24T08:16:34+00:00,https://www.defenseworld.net/2025/01/24/intertek-group-lonitrk-shares-pass-above-200-day-moving-average-time-to-sell.html,ITRK.L,Intertek Group plc,Intertek Group (LON:ITRK) Shares Pass Above 200 Day Moving Average – Time to Sell?,2025-01-24 08:16:34+00:00,2025-01-24,2025-01-27,5005.0
121,915a40fdc6c5ddf69abe240dea9100a62368b5cd094c31d789a717b5379ccf71,2025-01-25T20:46:14+00:00,https://www.modernreaders.com/news/2025/01/25/intertek-group-lonitrk-stock-price-passes-above-200-day-moving-average-whats-next.html,ITRK.L,Intertek Group plc,Intertek Group (LON:ITRK) Stock Price Passes Above 200 Day Moving Average – What's Next?,2025-01-25 20:46:14+00:00,2025-01-25,2025-01-27,5005.0
122,d64ddd724a330897cbf40c1f00c7458ba055c5afb5683821721bc4cc89435e99,2025-02-26T15:31:21+00:00,https://www.finanznachrichten.de/nachrichten-2025-02/64667757-gamechange-solar-s-genius-tracker-racking-verified-compatible-by-intertek-for-2kv-solar-projects-008.htm,ITRK.L,Intertek Group plc,GameChange Solar's Genius Tracker Racking Verified Compatible by Intertek for 2kV Solar Projects,2025-02-26 15:31:21+00:00,2025-02-26,2025-02-27,5080.0
123,b68cbe3c020b2d67d7edbc968737e62e4eb81e94ada72d42e69af3b32793eee6,2025-03-04T10:47:32+00:00,https://www.marketwatch.com/story/intertek-shares-rise-on-share-buyback-raised-margin-guidance-1bc81015,ITRK.L,Intertek Group plc,"Intertek Shares Rise on Share Buyback, Raised Margin Guidance",2025-03-04 10:47:32+00:00,2025-03-04,2025-03-05,5385.0
124,7791287cefcfa2ed825cf067b017247e19a617c67c133fadc1ba03cdf68daeb8,2025-03-04T11:32:45+00:00,https://www.sharecast.com/news/news-and-announcements/intertek-shares-jump-on-pound350m-buyback-dividend-hike--19087202.html,ITRK.L,Intertek Group plc,"Intertek shares jump on £350m buyback, dividend hike",2025-03-04 11:32:45+00:00,2025-03-04,2025-03-05,5385.0
125,7c5d138288af29e7936b96a7c872456296d25c01f807bad5203d98ef0975c3bc,2025-03-04T21:02:02+00:00,https://www.wkrb13.com/2025/03/04/short-interest-in-intertek-group-plc-otcmktsiktsy-drops-by-19-0.html,ITRK.L,Intertek Group plc,Short Interest in Intertek Group plc (OTCMKTS:IKTSY) Drops By 19.0%,2025-03-04 21:02:02+00:00,2025-03-04,2025-03-05,5385.0
126,e7d49db7346516b3313178dd77e89ea13a2f74e3425bcd664c64cc9d9bae7874,2025-03-05T01:02:04+00:00,https://www.dailypolitical.com/2025/03/04/intertek-group-otcmktsiktsy-sets-new-1-year-high-heres-why.html,ITRK.L,Intertek Group plc,Intertek Group (OTCMKTS:IKTSY) Sets New 1-Year High – Here's Why,2025-03-05 01:02:04+00:00,2025-03-05,2025-03-06,5255.0
127,1aad3735df75a643685827c6534267ff4d7330d7c1ed8e1b6a0397c2f0fa241a,2025-03-06T15:17:25+00:00,https://www.modernreaders.com/news/2025/03/06/intertek-group-lonitrk-issues-earnings-results.html,ITRK.L,Intertek Group plc,Intertek Group (LON:ITRK) Issues Earnings Results,2025-03-06 15:17:25+00:00,2025-03-06,2025-03-07,5210.0
128,a7d145e07186787a06192f4a90de7192b2673d51671a2f92bcfb3d09afc08e8f,2025-03-13T18:02:10+00:00,https://www.modernreaders.com/news/2025/03/13/intertek-group-plc-lonitrk-insider-sells-1972530-12-in-stock.html,ITRK.L,Intertek Group plc,"Intertek Group plc (LON:ITRK) Insider Sells £1,972,530.12 in Stock",2025-03-13 18:02:10+00:00,2025-03-13,2025-03-14,4876.0
129,7975cff0f2d4c4af5f6afd2e5b6ebd0106991a712b9aa81b2836107cc9e6001f,2025-03-13T18:02:19+00:00,https://www.themarketsdaily.com/2025/03/13/intertek-group-plc-lonitrk-insider-andre-lacroix-sells-39498-shares.html,ITRK.L,Intertek Group plc,"Intertek Group plc (LON:ITRK) Insider Andre Lacroix Sells 39,498 Shares",2025-03-13 18:02:19+00:00,2025-03-13,2025-03-14,4876.0
130,fb9c5655826472cc532975716f4c3a029e2f43730525dfb594c12265a99e5151,2025-03-14T20:46:52+00:00,https://www.dailypolitical.com/2025/03/14/insider-buying-intertek-group-plc-lonitrk-insider-purchases-121-shares-of-stock.html,ITRK.L,Intertek Group plc,Insider Buying: Intertek Group plc (LON:ITRK) Insider Purchases 121 Shares of Stock,2025-03-14 20:46:52+00:00,2025-03-14,2025-03-17,4878.0
131,dbf0b753708f1bacf1c3fc1743f472e46f3527f34ab06bf6fb74e60843f30a7b,2025-03-15T21:16:49+00:00,https://www.themarketsdaily.com/2025/03/15/intertek-group-plc-otcmktsiktsy-short-interest-update.html,ITRK.L,Intertek Group plc,Intertek Group plc (OTCMKTS:IKTSY) Short Interest Update,2025-03-15 21:16:49+00:00,2025-03-15,2025-03-17,4878.0
132,02c713512ba382b7d36109b25b42c94068db37e45de696b1d3a963ab0e5909cd,2025-03-24T11:02:08+00:00,https://www.directorstalkinterviews.com/intertek-group-plc-commences-share-buyback-programme/4121188994,ITRK.L,Intertek Group plc,Intertek Group Plc commences Share buyback programme,2025-03-24 11:02:08+00:00,2025-03-24,2025-03-25,4940.0
133,d73176ce240e48f338efcdfb9ef79b4d6e4a5155781dc8a3edd490ea87b93669,2025-04-01T08:31:52+00:00,https://www.finanznachrichten.de/nachrichten-2025-04/64989750-intertek-launches-comprehensive-suite-of-solutions-to-support-eudr-compliance-for-key-commodities-004.htm,ITRK.L,Intertek Group plc,Intertek Launches Comprehensive Suite of Solutions to Support EUDR Compliance for Key Commodities,2025-04-01 09:31:52+01:00,2025-04-01,2025-04-02,5015.0
134,8d859adef23e703f7213b02a6f7808f5605f7698d015390d4d89c165825a7913,2025-04-05T22:16:55+00:00,https://www.tickerreport.com/banking-finance/12904316/intertek-group-otcmktsiktsy-stock-passes-below-fifty-day-moving-average-whats-next.html,ITRK.L,Intertek Group plc,Intertek Group (OTCMKTS:IKTSY) Stock Passes Below Fifty Day Moving Average – What's Next?,2025-04-05 23:16:55+01:00,2025-04-05,2025-04-07,4404.0
135,e7e428237b68a1576cb32372145af864822fd5cd02e0d336198244d9912a0d85,2025-04-16T15:46:57+00:00,https://www.tickerreport.com/banking-finance/12917313/intertek-group-plc-lonitrk-insider-buys-99459-50-in-stock.html,ITRK.L,Intertek Group plc,"Intertek Group plc (LON:ITRK) Insider Buys £99,459.50 in Stock",2025-04-16 16:46:57+01:00,2025-04-16,2025-04-17,4502.0
136,ecd3865dd33e2bd1c9519442db8dd1718a0068c9bba486714c2e6940243505ae,2025-05-06T09:01:37+00:00,https://www.marketscreener.com/quote/stock/INTERTEK-GROUP-PLC-4003872/news/Intertek-buys-Brazilian-building-products-testing-firm-Tesis-49838212/,ITRK.L,Intertek Group plc,Intertek buys Brazilian building products testing firm Tesis,2025-05-06 10:01:37+01:00,2025-05-06,2025-05-07,4672.0
137,966cd3d6952f23a0210464040155c0cf30993502cf171cece9bbffbd8bf3775a,2025-05-22T13:47:32+00:00,https://www.morningstar.com/company-reports/1285940-we-remain-confident-in-interteks-premium-tic-and-assurance-strategy,ITRK.L,Intertek Group plc,We Remain Confident in Intertek's Premium TIC and Assurance Strategy,2025-05-22 14:47:32+01:00,2025-05-22,2025-05-23,4750.0
138,1dc43343f09313485a9edf3558a95e0c8948ed2b684e23de884a950900f6c67a,2025-05-25T06:16:33+00:00,https://www.themarketsdaily.com/2025/05/25/intertek-group-lonitrk-receives-hold-rating-from-shore-capital.html,ITRK.L,Intertek Group plc,"Intertek Group (LON:ITRK) Receives ""Hold"" Rating from Shore Capital",2025-05-25 07:16:33+01:00,2025-05-25,2025-05-27,4800.0
139,cd2fe9b08079eb6d565797cd8551d1ace4dae3dc63fff80b9a50ce286748b0fd,2025-05-27T12:32:06+00:00,https://www.dailypolitical.com/2025/05/27/intertek-group-plc-itrk-to-go-ex-dividend-on-may-29th.html,ITRK.L,Intertek Group plc,Intertek Group plc (ITRK) To Go Ex-Dividend on May 29th,2025-05-27 13:32:06+01:00,2025-05-27,2025-05-28,4770.0
140,9418bc9b5ec63f57d01a3bdfd93d8fdae2474e2adfe0a5948d2c3041e3fd1382,2025-09-13T08:32:07+00:00,https://www.tickerreport.com/banking-finance/13147963/intertek-gp-otcmktsiktsy-stock-passes-below-fifty-day-moving-average-time-to-sell.html,ITRK.L,Intertek Group plc,Intertek Gp (OTCMKTS:IKTSY) Stock Passes Below Fifty Day Moving Average – Time to Sell?,2025-09-13 09:32:07+01:00,2025-09-13,2025-09-15,4674.0
141,5728d4751ed2f2d6dc612f6b49d6c7f084eaf173ec0e3725c30f803afeca415d,2025-10-03T12:02:49+00:00,https://www.marketscreener.com/news/intertek-bofa-resumes-coverage-with-buy-rating-ce7d5bdfd88eff20,ITRK.L,Intertek Group plc,Intertek: BofA resumes coverage with buy rating,2025-10-03 13:02:49+01:00,2025-10-03,2025-10-06,4934.0
142,9e372c5717dc71b91dbc3374d22610ad782fa32aa7be063156cbd438a21f47e5,2025-10-30T11:02:20+00:00,https://www.tickerreport.com/banking-finance/13219363/intertek-group-lonitrk-stock-crosses-above-two-hundred-day-moving-average-whats-next.html,ITRK.L,Intertek Group plc,Intertek Group (LON:ITRK) Stock Crosses Above Two Hundred Day Moving Average – What's Next?,2025-10-30 11:02:20+00:00,2025-10-30,2025-10-31,5085.0
143,a6d2872810ea241f7df20cb4bee1039a48a5cbb9bc6d19aaaffcbfdb6d803a94,2025-11-09T17:31:54+00:00,https://www.themarketsdaily.com/2025/11/09/intertek-group-lonitrk-share-price-crosses-above-two-hundred-day-moving-average-whats-next.html,ITRK.L,Intertek Group plc,Intertek Group (LON:ITRK) Share Price Crosses Above Two Hundred Day Moving Average – What's Next?,2025-11-09 17:31:54+00:00,2025-11-09,2025-11-10,5000.0
144,df67df227d01129547d41a8aa895080a6f7152773e3d628bb684bf57905c25f6,2025-11-25T10:31:51+00:00,https://www.proactiveinvestors.com/companies/news/1083131/ftse-100-live-london-stocks-slip-into-red-led-by-beazley-compass-and-intertek-1083131.html,ITRK.L,Intertek Group plc,"FTSE 100 Live: London stocks slip into red, led by Beazley, Compass and Intertek",2025-11-25 10:31:51+00:00,2025-11-25,2025-11-26,4600.0
145,1ded34b17de18115f19faf111d2d150af4109d7edd0d9b36ca9500d4b3b5ee69,2025-11-26T10:02:20+00:00,https://www.marketscreener.com/news/intertek-buys-highly-complementary-professional-testing-laboratory-ce7d5ed2de8cf320,ITRK.L,Intertek Group plc,"Intertek buys ""highly complementary"" Professional Testing Laboratory",2025-11-26 10:02:20+00:00,2025-11-26,2025-11-27,4636.0
146,43ada9d74a3965311747ea44853b0a12c55e8ae01506523903623a4fa5e046b5,2025-11-27T13:32:41+00:00,https://www.webwire.com/ViewPressRel.asp?aId=347169,ITRK.L,Intertek Group plc,Intertek strengthens its products testing business with acquisition of leading flooring products testing company,2025-11-27 13:32:41+00:00,2025-11-27,2025-11-28,4640.0
147,08bcffcdc17223a255bb9c4f0c9c100d13b548df2d411b8c80413acccfd83605,2025-12-11T23:02:06+00:00,https://www.tickerreport.com/banking-finance/13288383/intertek-gp-otcmktsiktsy-sees-unusually-high-trading-volume-time-to-buy.html,ITRK.L,Intertek Group plc,Intertek Gp (OTCMKTS:IKTSY) Sees Unusually-High Trading Volume – Time to Buy?,2025-12-11 23:02:06+00:00,2025-12-11,2025-12-12,4418.0
148,b0378a9d0c77b9c557c93814e83f4d7d9f93c554eb5cdbfd7d469e78358850c2,2025-12-12T17:48:03+00:00,https://www.webwire.com/ViewPressRel.asp?aId=347906,ITRK.L,Intertek Group plc,"Intertek achieves TISAX® Assessment Level 3 Certification, enhancing position as trusted parter to automotive industry",2025-12-12 17:48:03+00:00,2025-12-12,2025-12-15,4444.0
149,2bf0b4389405bb601fcf34cd27b14aa9246af08ad84271cde4e204c73f9fe599,2025-12-23T07:17:24+00:00,https://www.dailypolitical.com/2025/12/22/intertek-group-plc-lonitrk-receives-gbx-5355-50-consensus-pt-from-analysts.html,ITRK.L,Intertek Group plc,"Intertek Group plc (LON:ITRK) Receives GBX 5,355.50 Consensus PT from Analysts",2025-12-23 07:17:24+00:00,2025-12-23,2025-12-24,4646.0

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
150,379a83e2e7f55b6a1d4c84110c20aa4df4d4f5e30916e481381918d86767f0cd,2025-01-04T11:46:14+00:00,https://www.dailymail.co.uk/news/article-14249551/National-Grid-abandons-new-electricity-pylons-noisy-blowing-17m-project.html,NG.L,National Grid plc,National Grid abandons new electricity pylons because they are too noisy - after blowing £17m on the project,2025-01-04 11:46:14+00:00,2025-01-04,2025-01-06,947.799988
151,ea8480217b7b381674d020a70ff9477989658336870d9d48887fa386ced88aca,2025-01-06T18:17:14+00:00,https://www.utilitydive.com/news/national-grid-con-edison-ferc-gas-pipeline-reliability-cold-weather/736519/,NG.L,National Grid plc,"National Grid, Con Edison urge FERC to adopt gas pipeline reliability requirements",2025-01-06 18:17:14+00:00,2025-01-06,2025-01-07,937.799988
152,5f7e328f4e2b3a5ab814bcc5dfe865200f1b4c37c5759765f5a5aa185eef8024,2025-02-04T23:17:15+00:00,https://www.newsday.com/long-island/national-grid-ibew-strike-vote-contract-irplpcd7,NG.L,National Grid plc,"Possible strike vote looms as National Grid, union continue contract talks",2025-02-04 23:17:15+00:00,2025-02-04,2025-02-05,981.200012
153,36386ed16c0934a0b25c118e67b31fdc7ca22685de312315fb19c3601e3e7c11,2025-02-09T22:16:39+00:00,https://www.bostonglobe.com/2025/02/09/science/national-grid-drops-lowell-networked-geothermal/,NG.L,National Grid plc,National Grid pulls plug on Lowell geothermal pilot,2025-02-09 22:16:39+00:00,2025-02-09,2025-02-10,981.400024
154,6f53d704f09db9fa3559341d6773d0210e2105464dee68234fb7c3bd338b6d6b,2025-02-16T19:01:44+00:00,https://cleantechnica.com/2025/02/16/uks-national-grid-does-some-mythbusting/,NG.L,National Grid plc,UK's National Grid Does Some Mythbusting,2025-02-16 19:01:44+00:00,2025-02-16,2025-02-17,953.200012
155,3dd9bfc8d1dfd7353f82c44ad3d4db6a3fdcea8fa62f594a87168272d5811936,2025-02-25T21:46:57+00:00,https://www.renewableenergyworld.com/energy-business/national-grid-sells-us-renewables-arm-to-brookfield-for-1-7bn/,NG.L,National Grid plc,National Grid sells US renewables arm to Brookfield for $1.7bn,2025-02-25 21:46:57+00:00,2025-02-25,2025-02-26,985.200012
156,84a9800dbd2f6435cbd08984a74766d23a6afaf474bfa8665a81fc3627acfb53,2025-03-07T19:46:30+00:00,https://naija247news.com/2025/03/07/national-grid-reportedly-collapses-as-ikedc-blames-blackout-on-system-outage/,NG.L,National Grid plc,National Grid Reportedly Collapses as IKEDC Blames Blackout on 'System Outage',2025-03-07 19:46:30+00:00,2025-03-07,2025-03-10,929.799988
157,30f3ad6fa17c5df8f6281f248e92ffe1b9e2c3dda3d4fd900cc535970b837d83,2025-03-17T17:01:44+00:00,http://readme.readmedia.com/FYI-NEW-NATIONAL-GRID-RATE-HIKES-GOING-INTO-EFFECT-IN-BROOKLYN-LONG-ISLAND-COMING-APRIL-1/20681287,NG.L,National Grid plc,"FYI: NEW NATIONAL GRID RATE HIKES GOING INTO EFFECT IN BROOKLYN, LONG ISLAND COMING APRIL 1",2025-03-17 17:01:44+00:00,2025-03-17,2025-03-18,975.000000
158,de9a6c4551f5cc803b60aa93d9e8922ee5fcf5f30553aac43608cbe3cf678ce1,2025-03-24T06:31:49+00:00,https://www.express.co.uk/news/uk/2031377/heathrow-slams-national-grid-boss,NG.L,National Grid plc,Heathrow slams National Grid boss who said airport had 'enough power' | UK | News,2025-03-24 06:31:49+00:00,2025-03-24,2025-03-25,966.000000
159,9fbfdb2025b437d8299ad1f4359396cb2aca700e03b5024e3f5d811ba55c6a1c,2025-03-24T10:47:25+00:00,https://www.firstpost.com/world/70mn-loss-200000-stranded-uk-national-grid-chief-says-heathrow-couldve-stayed-open-13874019.html,NG.L,National Grid plc,"£70mn loss, 200,000 stranded: UK national grid chief says Heathrow could've stayed open – Firstpost",2025-03-24 10:47:25+00:00,2025-03-24,2025-03-25,966.000000
160,cd054d62fe291ec59c487f28f46a6ecb62ab20337a27e824910773b7af9e2a72,2025-03-30T18:47:16+00:00,https://www.tickerreport.com/banking-finance/12896199/national-grid-plc-nysengg-short-interest-update.html,NG.L,National Grid plc,National Grid plc (NYSE:NGG) Short Interest Update,2025-03-30 19:47:16+01:00,2025-03-30,2025-03-31,1008.000000
161,15f0d5951cbf02555a817e1a24d0285d07885af12b9528b079dec53b18748583,2025-04-17T08:16:46+00:00,https://www.eadt.co.uk/news/25092254.national-grid-working-communities-lionlink-project/,NG.L,National Grid plc,National Grid working with communities on LionLink project | East Anglian Daily Times,2025-04-17 09:16:46+01:00,2025-04-17,2025-04-22,1076.500000
162,06f9a784081c39ba9b2d4a073e1f28fb9742129456f958bdddfdb8bf80dd61ee,2025-04-24T10:32:25+00:00,https://www.energy-pedia.com/news/general/national-grids-sea-link-project-moves-forward-as-application-accepted-by-planning-inspectorate-199610,NG.L,National Grid plc,National Grid's Sea Link project moves forward as application accepted by Planning Inspectorate,2025-04-24 11:32:25+01:00,2025-04-24,2025-04-25,1072.000000
163,38dc6600edaedb80c9b7919cb52d914f74646efe40b4be699be8ed50380475c1,2025-04-24T15:02:22+00:00,https://www.energy-pedia.com/news/united-kingdom/national-grids-sea-link-project-moves-forward-as-application-accepted-by-planning-inspectorate-199610,NG.L,National Grid plc,UK: National Grid's Sea Link project moves forward as application accepted by Planning Inspectorate,2025-04-24 16:02:22+01:00,2025-04-24,2025-04-25,1072.000000
164,c31e518e127cb07f01fc97d043b1f8a8f302d50061447e76d70b1e059b64823a,2025-05-02T08:01:47+00:00,https://www.proactiveinvestors.co.uk/companies/news/1070500/national-grid-falls-after-poaching-new-ceo-from-shell-1070500.html,NG.L,National Grid plc,National Grid falls after poaching new CEO from Shell,2025-05-02 09:01:47+01:00,2025-05-02,2025-05-06,1071.000000
165,dbe960c1cf20b6f82ef2116167cfdb46e5da4ebfd74452e8b515efc668560a86,2025-06-03T11:01:45+00:00,https://www.computerweekly.com/news/366625161/National-Grid-starts-building-large-scale-substation-to-support-growth-of-West-London-datacentres,NG.L,National Grid plc,National Grid starts building large-scale substation to support growth of West London datacentres,2025-06-03 12:01:45+01:00,2025-06-03,2025-06-04,1044.000000
166,940ca63477d8903fb40ba34b7ba981784de14a22eb2eef91ccb16e57a1b2d4b6,2025-06-06T09:17:07+00:00,https://www.fool.co.uk/2025/06/06/are-national-grid-shares-still-a-buy-to-consider-after-the-dividend-yield-falls-below-5/,NG.L,National Grid plc,Are National Grid shares still a buy to consider after the dividend yield falls below 5%?,2025-06-06 10:17:07+01:00,2025-06-06,2025-06-09,1035.000000
167,bf4caa1b4c5aab0fbd33a6c5da14c9c394d97220696a8517ec5ed280913d28e6,2025-06-08T13:16:17+00:00,https://www.dailypolitical.com/2025/06/08/national-grid-lonng-stock-price-down-0-4-time-to-sell.html,NG.L,National Grid plc,National Grid (LON:NG) Stock Price Down 0.4% – Time to Sell?,2025-06-08 14:16:17+01:00,2025-06-08,2025-06-09,1035.000000
168,d844d12336cf24833bb9797b4f3e266379ac80d73117dd6cffd1516c91f43aec,2025-06-09T18:32:08+00:00,https://www.berkshireeagle.com/news/northern_berkshires/williamstown-tree-removal-national-grid/article_14c4b6b5-fc10-4a79-abf6-19f426b8d4cf.html,NG.L,National Grid plc,National Grid plans to cut hundreds of trees in Williamstown. The tree warden says the plan has been carefully considered,2025-06-09 19:32:08+01:00,2025-06-09,2025-06-10,1040.500000
169,f30ba4882c2b1137d53fd435e7553706e3efa004d6e370f687d26cacd8d112aa,2025-09-24T15:03:13+00:00,https://www.marketscreener.com/news/bae-systems-appoints-outgoing-national-grid-ceo-pettigrew-to-board-ce7d58d2d981f020,NG.L,National Grid plc,BAE Systems appoints outgoing National Grid CEO Pettigrew to board,2025-09-24 16:03:13+01:00,2025-09-24,2025-09-25,1046.000000
170,716b4dfdb22556d55bfc174b9a65dcaefe7c3449a3b692b2c2b7f7a82018598c,2025-09-24T20:17:14+00:00,https://www.thebusinessdesk.com/westmidlands/news/2102960-national-grid-powers-energy-transition-with-brand-new-control-centre-on-brownfield-site/,NG.L,National Grid plc,National Grid powers energy transition with brand new control centre on brownfield site,2025-09-24 21:17:14+01:00,2025-09-24,2025-09-25,1046.000000
171,0fa695381e26d809682ac50b0e0815ca2c0091bbe8ba6a603716b744f2a28db1,2025-09-26T13:47:33+00:00,https://www.newcivilengineer.com/latest/national-grids-180km-power-line-from-norwich-to-tilbury-dco-progressed-26-09-2025/,NG.L,National Grid plc,National Grid's 180km power line from Norwich to Tilbury DCO progressed,2025-09-26 14:47:33+01:00,2025-09-26,2025-09-29,1061.500000
172,5cf064340ce69c20949f4db292f426478ce8abb622e9d6f71a3de57179cc4d32,2025-10-23T21:01:57+00:00,https://www.cubaheadlines.com/articles/313465,NG.L,National Grid plc,Widespread Power Outage Hits Havana Following Partial Collapse of National Grid,2025-10-23 22:01:57+01:00,2025-10-23,2025-10-24,1146.000000
173,6960a694312c622e25621a19fc22b4662dbc0b64af915994225e353a2aa4de06,2025-11-02T06:46:52+00:00,https://dailytrust.com/tariff-will-drop-with-more-industries-on-national-grid-adeshina/,NG.L,National Grid plc,Tariff Will Drop With More Industries On National Grid – Kola Adesina,2025-11-02 06:46:52+00:00,2025-11-02,2025-11-03,1138.500000
174,813bfde8725220847a65c13bf1807067fb375ecfec9cc3af7c00197a91d41be4,2025-11-06T16:17:58+00:00,https://www.fool.com/earnings/call-transcripts/2025/11/06/national-grid-ngg-q2-2026-earnings-transcript/?source=iedfolrf0000001,NG.L,National Grid plc,National Grid (NGG) Q2 2026 Earnings Transcript,2025-11-06 16:17:58+00:00,2025-11-06,2025-11-07,1164.000000
175,f44b78a0b1cf28617f576de0008efee44487a8a82b576faff9b81e607f883e35,2025-11-19T15:02:21+00:00,https://www.dailypolitical.com/2025/11/19/national-grid-transco-plc-ngg-to-go-ex-dividend-on-november-21st.html,NG.L,National Grid plc,"National Grid Transco, PLC (NGG) To Go Ex-Dividend on November 21st",2025-11-19 15:02:21+00:00,2025-11-19,2025-11-20,1138.000000
176,7248de7634a289e1fed18c985dfdae51e51a3ef7866628b7d6ef4af874119a3a,2025-12-10T08:02:15+00:00,https://www.shropshirelive.com/news/2025/12/10/national-grid-to-install-new-electricity-cables-in-shrewsbury-from-january/,NG.L,National Grid plc,National Grid to install new electricity cables in Shrewsbury from January,2025-12-10 08:02:15+00:00,2025-12-10,2025-12-11,1109.500000
177,959be79c135ca547df5ef9a0b41ae28532a6533e3910f63c9cce43f82ef77dcb,2025-12-18T11:17:40+00:00,https://www.thebusinessdesk.com/northwest/news/2164673-battery-energy-storage-venture-secures-key-infrastructure-agreement-with-national-grid/,NG.L,National Grid plc,Battery energy storage venture secures key infrastructure agreement with National Grid,2025-12-18 11:17:40+00:00,2025-12-18,2025-12-19,1144.000000
178,44e9c7f264898a975a23c9ad38af1e2630ba40346f1d16adba9e2d607df4ccfa,2025-12-29T17:47:33+00:00,https://punchng.com/blackout-as-national-grid-collapses-2/,NG.L,National Grid plc,"National Grid Collapses, Causing Widespread Blackout",2025-12-29 17:47:33+00:00,2025-12-29,2025-12-30,1139.000000
179,e8a52e4d81a23ec29c7f695fbcebd28fbac0172586f6cf92f40a0aa35e8fcc34,2025-12-31T02:02:49+00:00,https://www.wktv.com/news/local/national-grid-restores-power-to-95-of-customers-amid-winter-storm/article_94e9b27e-ce7e-4406-ad08-020c79422282.html,NG.L,National Grid plc,National Grid Restores Power to 95% of Customers Amid Winter Storm,2025-12-31 02:02:49+00:00,2025-12-31,2026-01-02,1138.000000

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
180,6c1e4d53f1471bd2c7db4ba8540aadf5265b3e4c77efc3f32dc0923aa68fdee4,2025-01-17T11:46:58+00:00,https://www.wkrb13.com/2025/01/17/relx-lonrel-hits-new-52-week-high-heres-why.html,REL.L,RELX plc,Relx (LON:REL) Hits New 52-Week High – Here's Why,2025-01-17 11:46:58+00:00,2025-01-17,2025-01-20,3949.0
181,778678afad5006c97b084be083c63cb77ff4a753c43abdee5bc7874563395343,2025-01-22T14:32:16+00:00,https://www.themarketsdaily.com/2025/01/22/relx-otcmktsrlxxf-trading-up-2-6-time-to-buy.html,REL.L,RELX plc,Relx (OTCMKTS:RLXXF) Trading Up 2.6% – Time to Buy?,2025-01-22 14:32:16+00:00,2025-01-22,2025-01-23,3996.0
182,f7d22ed6558154756c35f6ebb848e2011e1292179bd391813355556d2de15425,2025-01-29T09:46:54+00:00,https://www.themarketsdaily.com/2025/01/29/relx-lonrel-stock-price-passes-above-200-day-moving-average-should-you-sell.html,REL.L,RELX plc,Relx (LON:REL) Stock Price Passes Above 200-Day Moving Average – Should You Sell?,2025-01-29 09:46:54+00:00,2025-01-29,2025-01-30,3978.0
183,50586a4b56df6e98401dbef28266cbfe3caf4925aefe76458282041cc9ff6fcd,2025-01-31T09:47:09+00:00,https://www.insidermonkey.com/blog/relx-plc-relx-reports-10-profit-growth-in-h1-2024-driven-by-ai-powered-analytics-and-digital-transformation-1438731/,REL.L,RELX plc,"RELX PLC (RELX) Reports 10% Profit Growth in H1 2024, Driven by AI-Powered Analytics and Digital Transformation",2025-01-31 09:47:09+00:00,2025-01-31,2025-02-03,4014.0
184,93c7ae90a2917cc9ec05014964af3eb55122a336f28f464e63dcfa1ce4a534fa,2025-01-31T14:16:44+00:00,https://www.wkrb13.com/2025/01/31/relx-plc-nyserelx-shares-bought-by-hamilton-point-investment-advisors-llc.html,REL.L,RELX plc,Relx Plc (NYSE:RELX) Shares Bought by Hamilton Point Investment Advisors LLC,2025-01-31 14:16:44+00:00,2025-01-31,2025-02-03,4014.0
185,be65fcb0cc1ecc30fae6fd8a8ea29b2f9d38f87f09b72831e0107effd0d57f3c,2025-02-02T20:01:24+00:00,https://www.modernreaders.com/news/2025/02/02/relx-plc-otcmktsrlxxf-sees-large-increase-in-short-interest.html,REL.L,RELX plc,Relx Plc (OTCMKTS:RLXXF) Sees Large Increase in Short Interest,2025-02-02 20:01:24+00:00,2025-02-02,2025-02-03,4014.0
186,c7c61926b0ffe89456b6658fd259c3cb10d987d88f2cb8db65addd77a09d38cc,2025-02-02T22:46:35+00:00,https://theenterpriseleader.com/2025/02/02/relx-plc-otcmktsrlxxf-sees-significant-growth-in-short-interest.html,REL.L,RELX plc,Relx Plc (OTCMKTS:RLXXF) Sees Significant Growth in Short Interest,2025-02-02 22:46:35+00:00,2025-02-02,2025-02-03,4014.0
187,eaceccc8519e95ba206d97828fd36cdf7db124636b9dd20dd32c9baf04ea0326,2025-02-13T08:01:43+00:00,https://www.marketscreener.com/quote/stock/RELX-PLC-9590187/news/RELX-Pretax-Profit-Rises-on-Strong-Revenue-Growth-49046147/,REL.L,RELX plc,RELX Pretax Profit Rises on Strong Revenue Growth,2025-02-13 08:01:43+00:00,2025-02-13,2025-02-14,4148.0
188,6f762197f9c77338a89f44b4b0c280e4b4cb1aafaa4082c540583a6b3db4a507,2025-02-13T10:16:42+00:00,https://www.directorstalkinterviews.com/relx-plc-appoints-andy-halford-as-a-non-executive-director/4121186250,REL.L,RELX plc,RELX Plc appoints Andy Halford as a Non-Executive Director,2025-02-13 10:16:42+00:00,2025-02-13,2025-02-14,4148.0
189,dfd81a0daf35ef07b9afaa254fc96870391fe0ebba94b9e931e2813e0375ccc4,2025-02-13T15:31:47+00:00,https://www.tsnn.com/news/relx-reports-strong-2024-results-highlights-growth-aidriven-analytics-events-industry,REL.L,RELX plc,"RELX Reports Strong 2024 Results, Highlights Growth in AI-Driven Analytics for Events Industry",2025-02-13 15:31:47+00:00,2025-02-13,2025-02-14,4148.0
190,40a36cfe4f113c81f429ad5dfa4ba7775638de723b42344538dd58bc3cdd69db,2025-02-15T13:46:55+00:00,https://www.tickerreport.com/banking-finance/12837142/abc-arbitrage-sa-purchases-new-shares-in-relx-plc-nyserelx.html,REL.L,RELX plc,ABC Arbitrage SA Purchases New Shares in Relx Plc (NYSE:RELX),2025-02-15 13:46:55+00:00,2025-02-15,2025-02-17,4052.0
191,07a1ba9133b2f22b6f11adc13490ae47e75915f1e51f5cf96524ac19bd985173,2025-02-18T23:47:23+00:00,https://www.dailypolitical.com/2025/02/18/relx-plc-nyserelx-announces-semi-annual-dividend-of-0-56.html,REL.L,RELX plc,Relx Plc (NYSE:RELX) Announces Semi-annual Dividend of $0.56,2025-02-18 23:47:23+00:00,2025-02-18,2025-02-19,4047.0
192,cc4d2ecd29fd0a06db1e0315d2d25d13ef876cca26cba3362722026041b79499,2025-03-05T12:17:28+00:00,https://www.themarketsdaily.com/2025/03/05/5659-shares-in-relx-plc-nyserelx-purchased-by-lgt-group-foundation.html,REL.L,RELX plc,"5,659 Shares in Relx Plc (NYSE:RELX) Purchased by LGT Group Foundation",2025-03-05 12:17:28+00:00,2025-03-05,2025-03-06,3755.0
193,62976b1534cc0b05ce7ca1e73965e03e99c8ed5331597b7c4ddcf9f9a1c44ab9,2025-03-05T14:02:31+00:00,https://www.tickerreport.com/banking-finance/12862242/mission-wealth-management-lp-reduces-stock-position-in-relx-plc-nyserelx.html,REL.L,RELX plc,Mission Wealth Management LP Reduces Stock Position in Relx Plc (NYSE:RELX),2025-03-05 14:02:31+00:00,2025-03-05,2025-03-06,3755.0
194,74baabdb72302a6ecb811f55194cbc2b840862a7e6b8f197c851bec96c282bdd,2025-03-15T11:31:40+00:00,https://www.modernreaders.com/news/2025/03/15/218413-shares-in-relx-plc-nyserelx-purchased-by-connor-clark-lunn-investment-management-ltd.html,REL.L,RELX plc,"218,413 Shares in Relx Plc (NYSE:RELX) Purchased by Connor Clark & Lunn Investment Management Ltd.",2025-03-15 11:31:40+00:00,2025-03-15,2025-03-17,3779.0
195,0e8bd78cfd5df945070c75485b1c82c9a9dc69c59d5d6e264a74af3e8a8070cc,2025-03-15T12:31:35+00:00,https://www.modernreaders.com/news/2025/03/15/eversource-wealth-advisors-llc-grows-position-in-relx-plc-nyserelx.html,REL.L,RELX plc,EverSource Wealth Advisors LLC Grows Position in Relx Plc (NYSE:RELX),2025-03-15 12:31:35+00:00,2025-03-15,2025-03-17,3779.0
196,21623d738b81b9be4612709270c5380efa630c6e557955c1f77111d07fa4b983,2025-03-17T08:31:40+00:00,https://www.modernreaders.com/news/2025/03/17/sequoia-financial-advisors-llc-increases-stock-position-in-relx-plc-nyserelx.html,REL.L,RELX plc,Sequoia Financial Advisors LLC Increases Stock Position in Relx Plc (NYSE:RELX),2025-03-17 08:31:40+00:00,2025-03-17,2025-03-18,3815.0
197,bd55cafcc6be68ea7670e1ecebe393dba49f75cfe56f255bf20838f329459b7b,2025-03-18T09:32:27+00:00,https://www.dailypolitical.com/2025/03/18/frank-rimerman-advisors-llc-decreases-stock-holdings-in-relx-plc-nyserelx.html,REL.L,RELX plc,Frank Rimerman Advisors LLC Decreases Stock Holdings in Relx Plc (NYSE:RELX),2025-03-18 09:32:27+00:00,2025-03-18,2025-03-19,3769.0
198,9150bd18835d190e2738b3882f519c042c3747cb79a5fd92708a9ac3e681772a,2025-03-25T12:02:14+00:00,https://www.themarketsdaily.com/2025/03/25/keystone-investors-pte-ltd-has-255000-stock-holdings-in-relx-plc-nyserelx.html,REL.L,RELX plc,"Keystone Investors PTE Ltd. Has $255,000 Stock Holdings in Relx Plc (NYSE:RELX)",2025-03-25 12:02:14+00:00,2025-03-25,2025-03-26,3894.0
199,3c5dde2496f5907bf9cf8f6311d9226903bb5a358894f4c32dec14d183b51d2b,2025-03-26T13:32:04+00:00,https://www.themarketsdaily.com/2025/03/26/the-goldman-sachs-group-begins-coverage-on-relx-nyserelx.html,REL.L,RELX plc,The Goldman Sachs Group Begins Coverage on Relx (NYSE:RELX),2025-03-26 13:32:04+00:00,2025-03-26,2025-03-27,3849.0
200,689d1693ef4b3e9ec6800067c278b7f714c8ee52402670c35c736fa6857b1685,2025-03-29T08:01:39+00:00,https://www.wkrb13.com/2025/03/29/relx-nyserelx-now-covered-by-analysts-at-the-goldman-sachs-group.html,REL.L,RELX plc,Relx (NYSE:RELX) Now Covered by Analysts at The Goldman Sachs Group,2025-03-29 08:01:39+00:00,2025-03-29,2025-03-31,3870.0
201,21b6e441e7a51b785aa90f489aee7d153bd4ab1aba79e12b525fe70ed03846e5,2025-04-04T12:02:31+00:00,https://www.dailypolitical.com/2025/04/04/puzo-michael-j-increases-stock-position-in-relx-plc-nyserelx.html,REL.L,RELX plc,Puzo Michael J Increases Stock Position in Relx Plc (NYSE:RELX),2025-04-04 13:02:31+01:00,2025-04-04,2025-04-07,3658.0
202,707023b912b0d7044bd9a127d6b9043f34dfeee072cf35aed2d7404ca9e0f828,2025-04-05T08:31:30+00:00,https://theenterpriseleader.com/2025/04/05/4387-shares-in-relx-plc-nyserelx-bought-by-highpoint-advisor-group-llc.html,REL.L,RELX plc,"4,387 Shares in Relx Plc (NYSE:RELX) Bought by HighPoint Advisor Group LLC",2025-04-05 09:31:30+01:00,2025-04-05,2025-04-07,3658.0
203,e9600a082e71f389d08a4a55af3ee899b702c71062ebe131d1b5eb7d7962fb2c,2025-04-24T07:01:33+00:00,https://www.marketscreener.com/quote/stock/RELX-PLC-9590187/news/RELX-Confirms-Guidance-After-Good-Start-to-Year-49700692/,REL.L,RELX plc,RELX Confirms Guidance After Good Start to Year,2025-04-24 08:01:33+01:00,2025-04-24,2025-04-25,3981.0
204,0f997a89812a523e138ac1d756ba03d0eaef3b29179cccc02c316241092f283d,2025-04-24T08:46:54+00:00,https://www.marketscreener.com/quote/stock/RELX-PLC-9590187/news/Relx-reaffirms-positive-outlook-as-business-mix-shift-drives-growth-49702084/,REL.L,RELX plc,Relx reaffirms positive outlook as business mix shift drives growth,2025-04-24 09:46:54+01:00,2025-04-24,2025-04-25,3981.0
205,83c7770886aff08f33a47c102ddc3cb50a91383af3c93a473ca80f171f19a824,2025-09-15T22:32:05+00:00,https://quicknews-africa.net/relx-international-launches-relx-pledge-initiative-enhancing-companys-global-commitment-to-corporate-accountability/,REL.L,RELX plc,"RELX INTERNATIONAL Launches RELX Pledge Initiative, Enhancing Companyâ€™s Global Commitment to Corporate Accountability",2025-09-15 23:32:05+01:00,2025-09-15,2025-09-16,3444.0
206,42295ddf5d8cfdf2bbb010ee07351d46e5b5e559221bbfdbe1098712cfe13af4,2025-10-06T17:16:59+00:00,https://www.proactiveinvestors.co.uk/companies/news/1079775/relx-is-an-ai-winner-with-catalysts-coming-says-ubs-1079775.html,REL.L,RELX plc,"RELX is 'an AI winner' with catalysts coming, says UBS",2025-10-06 18:16:59+01:00,2025-10-06,2025-10-07,3449.0
207,01bcb412981ffb5ed4fb06b24e543d33e1744cf75b1bbf91a926c29742ee23d7,2025-10-23T16:32:40+00:00,https://www.sharecast.com/news/news-and-announcements/relx-reports-strong-trading-momentum--21087208.html,REL.L,RELX plc,Relx reports strong trading momentum - Sharecast.com,2025-10-23 17:32:40+01:00,2025-10-23,2025-10-24,3471.0
208,e03857da1416b4f7790063be148d2281693b8dfd40bd8d57178bbd870fd466a9,2025-11-04T10:02:26+00:00,https://www.dailypolitical.com/2025/11/04/relx-plc-relx-shares-bought-by-assetmark-inc.html,REL.L,RELX plc,Relx Plc $RELX Shares Bought by Assetmark Inc.,2025-11-04 10:02:26+00:00,2025-11-04,2025-11-05,3391.0
209,612d354ef962ecec40f726244af651c163b27ede3fa36ac56b6914da1f959cdf,2025-12-11T03:17:12+00:00,https://www.tickerreport.com/banking-finance/13287022/relx-lonrel-hits-new-52-week-low-time-to-sell.html,REL.L,RELX plc,Relx (LON:REL) Hits New 52-Week Low – Time to Sell?,2025-12-11 03:17:12+00:00,2025-12-11,2025-12-12,3007.0

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
210,fc5386ee4fdc5e4182366813b1f0dabbbd33b7f548333b0e35458a0aea82c004,2025-01-08T00:02:05+00:00,https://www.fool.com.au/2025/01/08/as-the-rio-tinto-share-price-drops-should-i-buy-more/,RIO.L,Rio Tinto plc,"As the Rio Tinto share price drops, should I buy more?",2025-01-08 00:02:05+00:00,2025-01-08,2025-01-09,4747.5
211,f82d1bfa1a4b362e2a56737a660fff49c18f2b0dfe29109d3870ab28360e9395,2025-01-15T05:31:56+00:00,https://www.sharecast.com/news/broker-recommendations-/broker-tips--18541400.html,RIO.L,Rio Tinto plc,"Broker tips: Rio Tinto, Clarkson - Sharecast.com",2025-01-15 05:31:56+00:00,2025-01-15,2025-01-16,4985.0
212,eea34d5c8fa8b3bd87768ff3758392d9d9e633ebd815b6b91ccc8c5d2e5a2d7b,2025-01-16T22:31:36+00:00,https://www.thetimes.com/business-money/companies/article/rio-tinto-and-glencore-in-merger-talks-dlp2w505s,RIO.L,Rio Tinto plc,Rio Tinto and Glencore 'in merger talks',2025-01-16 22:31:36+00:00,2025-01-16,2025-01-17,4988.5
213,5d9f88f488e1a5ec7b29d637a636b3f8cedc8086056611db907535e171f97047,2025-01-16T23:02:09+00:00,https://www.fool.com.au/2025/01/17/should-you-buy-rio-tinto-shares-after-the-miners-update-2/,RIO.L,Rio Tinto plc,Should you buy Rio Tinto shares after the miner's update?,2025-01-16 23:02:09+00:00,2025-01-16,2025-01-17,4988.5
214,e57089996eec4a0f2412ebf05be89ad19dbcdf9c36c3ece8d6a223faa20219dc,2025-01-17T11:17:21+00:00,https://theenterpriseleader.com/2025/01/17/ritholtz-wealth-management-has-4-42-million-stock-position-in-rio-tinto-group-nyserio.html,RIO.L,Rio Tinto plc,Ritholtz Wealth Management Has $4.42 Million Stock Position in Rio Tinto Group (NYSE:RIO),2025-01-17 11:17:21+00:00,2025-01-17,2025-01-20,5015.0
215,6340873c76e1b37a122bcbcfc5821a584c1ba7ad355be4f4021faf1a4c327e44,2025-01-22T02:16:49+00:00,https://www.proactiveinvestors.com/companies/news/1064795/sovereign-metals-lifts-confidence-in-kasiya-project-with-optimised-pre-feasibility-study-supported-by-rio-tinto-1064795.html,RIO.L,Rio Tinto plc,Sovereign Metals lifts confidence in Kasiya Project with optimised pre-feasibility study supported by Rio Tinto,2025-01-22 02:16:49+00:00,2025-01-22,2025-01-23,4951.0
216,2fb17c6d316cd94ab7d5ece2fe867110e5eae2dc20b72b08f4e7f9581ff98ae1,2025-01-22T18:46:35+00:00,https://republicofmining.com/2025/01/22/can-a-rio-tinto-glencore-merger-supercharge-the-race-to-net-zero-by-jennifer-l-carbon-credits-january-21-2025/,RIO.L,Rio Tinto plc,"Can a Rio Tinto-Glencore Merger Supercharge the Race to Net Zero? – by Jennifer L (Carbon Credits – January 21, 2025)",2025-01-22 18:46:35+00:00,2025-01-22,2025-01-23,4951.0
217,846fa0934d661af476964a3cf9366471a595f3843a0d374c31c3680cca80dff9,2025-01-28T06:16:30+00:00,https://www.afr.com/policy/energy-and-climate/qld-hits-pause-on-wind-farms-and-big-miners-are-among-those-worried-20250123-p5l6md,RIO.L,Rio Tinto plc,Rnewable energy: Rio Tinto and BHP among big companies affected by Queensland's Crisafulli government decision to reassess wind farm projects,2025-01-28 06:16:30+00:00,2025-01-28,2025-01-29,4796.5
218,c4ad3a4cd97b7070086dde580c09aaf84e88e0b55ac37270adc6326114dcb82f,2025-01-31T11:31:57+00:00,https://www.insidermonkey.com/blog/rio-tinto-group-rio-faces-6-stock-decline-amid-copper-tariff-concerns-and-slower-ai-chip-demand-1438735/,RIO.L,Rio Tinto plc,Rio Tinto Group (RIO) Faces 6% Stock Decline Amid Copper Tariff Concerns and Slower AI Chip Demand,2025-01-31 11:31:57+00:00,2025-01-31,2025-02-03,4775.5
219,07aac437b298b5ff7cbe4d71a34f9410e5ffcdabd3f7393ecc36b72b64821795,2025-02-01T11:16:40+00:00,https://www.tickerreport.com/banking-finance/12818601/pfg-investments-llc-increases-holdings-in-rio-tinto-group-nyserio.html,RIO.L,Rio Tinto plc,PFG Investments LLC Increases Holdings in Rio Tinto Group (NYSE:RIO),2025-02-01 11:16:40+00:00,2025-02-01,2025-02-03,4775.5
220,a3c707d144b77bd4c910f3d422ff4a2ed78597e5b8c5be3985c77f658a65525a,2025-02-12T01:16:40+00:00,https://www.miragenews.com/rio-tinto-pledges-a750k-for-queensland-flood-1406854/,RIO.L,Rio Tinto plc,Rio Tinto Pledges A$750K for Queensland Flood Relief,2025-02-12 01:16:40+00:00,2025-02-12,2025-02-13,5020.0
221,846c525fa6c6411cb5b9ae0005e21e3d84a3baeb0b29eda372acc93767893fd8,2025-02-20T08:17:03+00:00,https://www.hurriyetdailynews.com/rio-tinto-propels-profits-with-strong-copper-sales-206035,RIO.L,Rio Tinto plc,Rio Tinto propels profits with strong copper sales,2025-02-20 08:17:03+00:00,2025-02-20,2025-02-21,5101.0
222,3f7c8c78096e39d961bcfd8eee7ccc453e87b74638dac5b71cc3fabb35597591,2025-02-20T13:16:53+00:00,https://www.thetimes.com/business-money/companies/article/rio-tinto-urges-investors-to-reject-call-to-scrap-london-listing-vvcnrlqdz,RIO.L,Rio Tinto plc,Rio Tinto urges investors to reject call to scrap London listing,2025-02-20 13:16:53+00:00,2025-02-20,2025-02-21,5101.0
223,7bce00821fc075e80f4d19cd49e8e12603ab8870eb83312238e09b71298f1d24,2025-02-20T23:16:59+00:00,https://slguardian.org/rio-tinto-faces-earnings-decline-amid-weaker-iron-ore-prices-and-inflationary-pressures/,RIO.L,Rio Tinto plc,Rio Tinto Faces Earnings Decline Amid Weaker Iron Ore Prices and Inflationary Pressures,2025-02-20 23:16:59+00:00,2025-02-20,2025-02-21,5101.0
224,e1d4dff2d4b4be11fd31ce61dbc79cc5f3fc14a4d68ddd5c2df871e05505fd7f,2025-02-21T05:16:29+00:00,https://www.law360.com:443/articles/2300810,RIO.L,Rio Tinto plc,Ex-Rio Tinto CFO Must Keep Fighting SEC Fraud Case,2025-02-21 05:16:29+00:00,2025-02-21,2025-02-24,5014.0
225,9f7011314b1dcea254f36f007435948b59583869872ac5f774c9fd1f661fac68,2025-03-07T02:16:53+00:00,https://www.proactiveinvestors.co.uk/companies/news/1067537/rio-tinto-finalises-6-7-billion-acquisition-of-arcadium-lithium-1067537.html,RIO.L,Rio Tinto plc,Rio Tinto finalises $6.7 billion acquisition of Arcadium Lithium,2025-03-07 02:16:53+00:00,2025-03-07,2025-03-10,4890.5
226,0510a380b070833eb06394cc9cbf76b694ab05ba75597619ff937400a8c6f229,2025-03-11T09:17:10+00:00,https://www.afr.com/companies/mining/rio-investor-warns-it-faces-a-brexit-moment-with-london-listing-vote-20250311-p5linv,RIO.L,Rio Tinto plc,RIO ASX: Rio Tinto investor WaveStone Capital warns against London-listing vote being pushed by Palliser Capital,2025-03-11 09:17:10+00:00,2025-03-11,2025-03-12,4765.5
227,d0fa38e274c709a79f80c994e44a84c478dac32ed4b5361530ba54b2895e0e5e,2025-04-03T23:46:39+00:00,https://www.miragenews.com/rio-tinto-boosts-aussie-supplier-spend-to-a17-7b-1438805/,RIO.L,Rio Tinto plc,Rio Tinto Boosts Aussie Supplier Spend to A$17.7B,2025-04-04 00:46:39+01:00,2025-04-04,2025-04-07,4074.5
228,36235464e77d5eb47f79686991bf0621e5e0769cb3ca92c6db9f02fc68c1ae3e,2025-04-16T12:02:30+00:00,https://www.marketscreener.com/quote/stock/RIO-TINTO-PLC-9590196/news/Rio-Tinto-Q1-production-hit-by-storm-49633242/,RIO.L,Rio Tinto plc,Rio Tinto: Q1 production hit by storm,2025-04-16 13:02:30+01:00,2025-04-16,2025-04-17,4356.5
229,8ebb7fd0b9cbbd0fa983671c5fecb5dd4cffc4064b427d6fa4657e5da8474ac8,2025-05-07T10:47:18+00:00,https://www.architectureanddesign.com.au/project/Rio-Tinto-HQ-Woods-Bagot,RIO.L,Rio Tinto plc,Rio Tinto HQ | Woods Bagot | Architecture & Design,2025-05-07 11:47:18+01:00,2025-05-07,2025-05-08,4514.0
230,b65e86c58bcab1f1ef8ddde0ff9a2ad1708bda6eb19304d354cd5dee41efb394,2025-05-21T23:16:46+00:00,https://www.finanznachrichten.de/nachrichten-2025-05/65471325-rio-tinto-to-start-early-works-and-final-studies-to-increase-amrun-mine-s-bauxite-production-on-queensland-s-cape-york-peninsula-004.htm,RIO.L,Rio Tinto plc,Rio Tinto to start early works and final studies to increase Amrun mine's bauxite production on Queensland's Cape York Peninsula,2025-05-22 00:16:46+01:00,2025-05-22,2025-05-23,4555.0
231,08b1564660b08572eef42ce0b32d60ee9a6d93664478f1c093d85777e4dc547f,2025-05-22T06:46:51+00:00,https://www.investegate.co.uk/announcement/rns/rio-tinto--rio/rio-tinto-chief-executive-succession-plan/8892013,RIO.L,Rio Tinto plc,Rio Tinto - Chief Executive succession plan | Company Announcement,2025-05-22 07:46:51+01:00,2025-05-22,2025-05-23,4555.0
232,c3b884d570118c5e8994152b2675112bb0ac139f149b6437d9fc7434b223c712,2025-06-12T08:31:51+00:00,https://portal.sina.com.hk/finance/finance-globenewswire/globenewswire/2025/06/12/1210994/rio-tinto-selects-imanage-to-support-legal-transformation-across-global-operations/,RIO.L,Rio Tinto plc,Rio Tinto Selects iManage to Support Legal Transformation Across Global Operations,2025-06-12 09:31:51+01:00,2025-06-12,2025-06-13,4251.0
233,f16f4688198ae74b7b09426f6625f7f0dba0baa81931660b7c99ba801f3335ca,2025-09-22T12:17:42+00:00,https://news.az/news/us-seeks-scandium-oxide-from-rio-tinto-for-defense-stockpile,RIO.L,Rio Tinto plc,U.S. seeks scandium oxide from Rio Tinto for defense stockpile,2025-09-22 13:17:42+01:00,2025-09-22,2025-09-23,4684.5
234,06ce422a619035e523bbf44ec97be1f9d1cd313ed2ce460253b881640c0fef27,2025-09-22T15:17:15+00:00,https://www.diamondworld.net/news/rio-tinto-announces-final-beyond-rare-diamond-tender,RIO.L,Rio Tinto plc,Rio Tinto Announces Final 'Beyond Rare' Diamond Tender,2025-09-22 16:17:15+01:00,2025-09-22,2025-09-23,4684.5
235,89ab805315494537311ce0b2e66923f07e4cc1af0a116a3dafccd5026c6e6409,2025-10-14T15:32:30+00:00,https://me.smenet.org/rio-tinto-says-strong-year-end-iron-ore-push-needed-as-china-demand-surges/,RIO.L,Rio Tinto plc,Rio Tinto says strong year-end iron ore push needed as China demand surges - Mining Engineering Online,2025-10-14 16:32:30+01:00,2025-10-14,2025-10-15,5135.0
236,4cb08344438426be616a1e2c3fa08c33dd8f0e1a44832c253d255b3f784941e7,2025-10-25T06:47:12+00:00,https://www.dailypolitical.com/2025/10/24/insider-selling-rio-tinto-group-lonrio-insider-sells-203-28-in-stock.html,RIO.L,Rio Tinto plc,Insider Selling: Rio Tinto Group (LON:RIO) Insider Sells £203.28 in Stock,2025-10-25 07:47:12+01:00,2025-10-25,2025-10-28,5294.0
237,37f8b42291c989fec23444a465160225053fb11680f7894f00ea9f4d056b7ed8,2025-10-29T12:32:40+00:00,https://www.themarketsdaily.com/2025/10/29/whalen-wealth-management-inc-makes-new-investment-in-rio-tinto-plc-rio.html,RIO.L,Rio Tinto plc,Whalen Wealth Management Inc. Makes New Investment in Rio Tinto PLC $RIO,2025-10-29 12:32:40+00:00,2025-10-29,2025-10-30,5460.0
238,25d195b164d6dbf27255844d2a37bba4c05cb1fd6659d7407b247e96bd2ce59d,2025-11-17T11:17:19+00:00,https://www.argusmedia.com/en/news-and-insights/latest-market-news/2754701-rio-tinto-supports-australian-low-co2-iron-plant,RIO.L,Rio Tinto plc,Rio Tinto supports Australian low-CO2 iron plant,2025-11-17 11:17:19+00:00,2025-11-17,2025-11-18,5220.0
239,328573983835dde6e29a7c2c9a1639f4bcc090e0afe524f58226e6910276cf50,2025-12-04T15:47:16+00:00,https://www.marketscreener.com/news/rio-tinto-s-new-ceo-targets-cost-cuts-asset-2-ce7d51dfde8ff527,RIO.L,Rio Tinto plc,"Rio Tinto's New CEO Targets Cost Cuts, Asset -2-",2025-12-04 15:47:16+00:00,2025-12-04,2025-12-05,5550.0

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
240,0ca0ca60dc5def9dc725dd363a876bf57dcae186c9e6d42f5d571c2ca8578432,2025-01-04T18:31:50+00:00,https://www.healio.com/news/orthopedics/20250104/smith-nephew-receives-fda-clearance-of-preoperative-planning-modeling-solution-for-tha,SN.L,Smith & Nephew plc,"Smith & Nephew receives FDA clearance of preoperative planning, modeling solution for THA",2025-01-04 18:31:50+00:00,2025-01-04,2025-01-06,980.000000
241,83c079de9c4076ed56da0fc8e82bf20bceb7095370e4a114b804808d7c7ab2db,2025-01-14T13:17:12+00:00,https://www.finanznachrichten.de/nachrichten-2025-01/64286162-smith-nephew-uk-ltd-smith-nephew-s-allevyn-life-sacrum-foam-dressing-and-leaf-patient-monitoring-system-receive-favorable-evidence-bar-ratings-fr-399.htm,SN.L,Smith & Nephew plc,Smith & Nephew UK Ltd: Smith+Nephew's ALLEVYN LIFE Sacrum Foam Dressing and LEAF Patient Monitoring System receive 'favorable' Evidence Bar ratings from ECRI for pressure injury prevention,2025-01-14 13:17:12+00:00,2025-01-14,2025-01-15,982.599976
242,cceac4dfa7034b18333271acdb019932db05eda20f4994d31563dfe11d34ea4c,2025-01-14T19:02:29+00:00,https://www.wkrb13.com/2025/01/14/smith-nephews-sn-overweight-rating-reiterated-at-jpmorgan-chase-co.html,SN.L,Smith & Nephew plc,"Smith & Nephew's (SN) ""Overweight"" Rating Reiterated at JPMorgan Chase & Co.",2025-01-14 19:02:29+00:00,2025-01-14,2025-01-15,982.599976
243,e24a3c736f6a3a0726043c52e6e6aa0260e1617b5d587de544a0ccfb1ce70572,2025-02-25T08:46:47+00:00,https://www.rttnews.com/3515692/smith-nephew-reports-improved-results-in-fy24-guides-fy25-revenue-growth-of-about-5.aspx,SN.L,Smith & Nephew plc,"Smith & Nephew Reports Improved Results In FY24, Guides FY25 Revenue Growth Of About 5%",2025-02-25 08:46:47+00:00,2025-02-25,2025-02-26,1111.000000
244,f41fba2572ca247ed9a1f7122c2a387a8dab59622379f9aeddf76120eff0d7d1,2025-02-25T09:31:19+00:00,https://www.aol.co.uk/hip-replacement-firm-smith-nephew-091207349.html,SN.L,Smith & Nephew plc,Hip replacement firm Smith & Nephew's profit surges amid recovery in US sales,2025-02-25 09:31:19+00:00,2025-02-25,2025-02-26,1111.000000
245,17a225b5242ec94df097bedeb581933233b9db422589a63221dc280ee96735ea,2025-02-25T09:32:04+00:00,https://www.investegate.co.uk:443/across-the-markets/across-the-markets-smith-nephew-wood-group-lion-finance,SN.L,Smith & Nephew plc,"Across The Markets: Smith & Nephew, Wood Group, Lion Finance",2025-02-25 09:32:04+00:00,2025-02-25,2025-02-26,1111.000000
246,db5408fda82c43c2babeeca292d8b0678db021377a59d1797de93c4f6dd87891,2025-02-25T12:47:18+00:00,https://www.rttnews.com/3515720/ftse-advances-smith-nephew-climb-higher-on-results.aspx,SN.L,Smith & Nephew plc,FTSE Advances; Smith & Nephew Climb Higher On Results,2025-02-25 12:47:18+00:00,2025-02-25,2025-02-26,1111.000000
247,4c7cb09f17d778b7a70df1362378368f5d42aa60a324b1eb15f1860043904d96,2025-02-25T19:02:37+00:00,https://www.proactiveinvestors.co.uk/companies/news/1066809/ftse-100-up-smith-nephew-surges-bae-gets-uk-defence-boost-1066809.html,SN.L,Smith & Nephew plc,FTSE 100 up; Smith & Nephew surges; BAE gets UK defence boost,2025-02-25 19:02:37+00:00,2025-02-25,2025-02-26,1111.000000
248,56e1818240f27018560ba8270818f1c5882e9ce61ecf4e2c92eeade2d303938e,2025-02-27T22:46:52+00:00,https://www.tickerreport.com/banking-finance/12853960/smith-nephew-plc-nysesnn-announces-dividend-increase-0-45-per-share.html,SN.L,Smith & Nephew plc,Smith & Nephew plc (NYSE:SNN) Announces Dividend Increase – $0.45 Per Share,2025-02-27 22:46:52+00:00,2025-02-27,2025-02-28,1142.000000
249,d4df5c53f28b56a91bb23c40570d893f8640a0954abe93940db85eecbbcae7e3,2025-03-01T13:47:03+00:00,https://theenterpriseleader.com/2025/03/01/smith-nephew-plc-nysesnn-shares-sold-by-henry-james-international-management-inc.html,SN.L,Smith & Nephew plc,Smith & Nephew plc (NYSE:SNN) Shares Sold by Henry James International Management Inc.,2025-03-01 13:47:03+00:00,2025-03-01,2025-03-03,1150.000000
250,c5ac054289237adb4903ce98e876b4574f6477d79dd0235e1dfa7d64d1136ebc,2025-03-03T15:01:46+00:00,https://www.investorschronicle.co.uk/content/770fb056-584d-5e24-b53f-610a511a9369,SN.L,Smith & Nephew plc,"Rolls Royce, banking stocks and Smith & Nephew",2025-03-03 15:01:46+00:00,2025-03-03,2025-03-04,1174.000000
251,dec9a8e2d67b57fef1726ee86d36ca004f159fc1fa0f41ab83fa59aea6340433,2025-03-18T07:46:48+00:00,https://www.modernreaders.com/news/2025/03/18/rewalk-robotics-nasdaqlfwd-versus-smith-nephew-nysesnn-critical-analysis.html,SN.L,Smith & Nephew plc,ReWalk Robotics (NASDAQ:LFWD) versus Smith & Nephew (NYSE:SNN) Critical Analysis,2025-03-18 07:46:48+00:00,2025-03-18,2025-03-19,1103.000000
252,f25bcc977ee0a07efae931dbdbdc81b0a9ccf33f22d35321abc0e308a53ce825,2025-04-14T09:17:18+00:00,https://www.tickerreport.com/banking-finance/12914102/bank-of-montreal-can-sells-31891-shares-of-smith-nephew-plc-nysesnn.html,SN.L,Smith & Nephew plc,"Bank of Montreal Can Sells 31,891 Shares of Smith & Nephew plc (NYSE:SNN)",2025-04-14 10:17:18+01:00,2025-04-14,2025-04-15,992.599976
253,9b243b206ddf2499157021a2b8b0e06c30a86d682a02f4eeed55b8eecffc28c3,2025-04-18T10:17:21+00:00,https://www.modernreaders.com/news/2025/04/18/bridgewater-associates-lp-boosts-holdings-in-smith-nephew-plc-nysesnn.html,SN.L,Smith & Nephew plc,Bridgewater Associates LP Boosts Holdings in Smith & Nephew plc (NYSE:SNN),2025-04-18 11:17:21+01:00,2025-04-18,2025-04-22,967.799988
254,27b331b32166e06aab43dcafc3c39b2d89b9bfe163ef785f46591a9025f75e88,2025-06-05T01:16:48+00:00,https://www.harrismartin.com/publications/4/drugs/articles/64915/wis-federal-judge-refuses-to-remand-smith-nephew-knee-replacement-action/,SN.L,Smith & Nephew plc,Wis. Federal Judge Refuses to Remand Smith & Nephew Knee Replacement Action,2025-06-05 02:16:48+01:00,2025-06-05,2025-06-06,1120.500000
255,5f3d995638c13541b37c629b787c0aefa229907cf182634b306c8294d337f5ca,2025-06-13T07:32:07+00:00,https://www.directorstalkinterviews.com/smith-nephew-appoints-david-king-as-non-executive-director/4121202005,SN.L,Smith & Nephew plc,Smith & Nephew appoints David King as Non-Executive Director,2025-06-13 08:32:07+01:00,2025-06-13,2025-06-16,1092.000000
256,4fb9c353aa76e59432999c993ed327f97082c7e5fab33c95647029f8daa03481,2025-09-30T08:01:45+00:00,https://www.finanznachrichten.de/nachrichten-2025-09/66572454-smith-nephew-cfo-john-rogers-to-relocate-to-us-020.htm,SN.L,Smith & Nephew plc,Smith & Nephew CFO John Rogers To Relocate To US,2025-09-30 09:01:45+01:00,2025-09-30,2025-10-01,1350.000000
257,50391bde89b1a5a34867a8dca28c89c70a509219471b1d977ba0a86f60ad0127,2025-09-30T10:47:45+00:00,https://www.dailymail.co.uk/money/markets/article-15147871/smith-nephew-finance-chief-follows-executives-US.html,SN.L,Smith & Nephew plc,Smith & Nephew finance chief follows other executives to the US,2025-09-30 11:47:45+01:00,2025-09-30,2025-10-01,1350.000000
258,aac70b7a6d3e91c501e92ff84bddb5256d804633db30bebbf4d2863ff0e6514c,2025-09-30T18:02:28+00:00,https://www.thetimes.com/business-money/companies/article/smith-and-nephew-finance-boss-john-rogers-to-relocate-to-america-3mzs5qrc2,SN.L,Smith & Nephew plc,Smith & Nephew finance boss John Rogers to relocate to America,2025-09-30 19:02:28+01:00,2025-09-30,2025-10-01,1350.000000
259,bbc7080600f9dbbe165a295096da2ac334b45e1b05d5eba6b5ec0ae653e2d197,2025-10-01T17:32:19+00:00,https://www.finanznachrichten.de/nachrichten-2025-10/66593234-smith-nephew-plc-smith-nephew-launches-coriograph-pre-op-planning-and-modeling-services-for-total-shoulder-arthroplasty-399.htm,SN.L,Smith & Nephew plc,Smith & Nephew Plc: Smith+Nephew launches CORIOGRAPH Pre-Op Planning and Modeling Services for total shoulder arthroplasty,2025-10-01 18:32:19+01:00,2025-10-01,2025-10-02,1346.500000
260,565b9d734755f0ea0e32fb5d5e430b6701467b3148dea0d031e333ac5c08ff76,2025-10-07T09:47:20+00:00,https://www.dailypolitical.com/2025/10/07/smith-nephew-lonsn-shares-pass-above-two-hundred-day-moving-average-whats-next.html,SN.L,Smith & Nephew plc,Smith & Nephew (LON:SN) Shares Pass Above Two Hundred Day Moving Average – What's Next?,2025-10-07 10:47:20+01:00,2025-10-07,2025-10-08,1336.000000
261,31ce7af70cd5e96697c4450883b042321c5bf299f52e9b30740c67d0b7e50181,2025-10-20T11:47:29+00:00,https://www.insidermonkey.com/blog/moodys-upgrades-smith-nephew-snn-long-term-rating-citing-strong-revenue-and-margin-growth-1630207/,SN.L,Smith & Nephew plc,"Moody's Upgrades Smith & Nephew (SNN) Long-Term Rating, Citing Strong Revenue and Margin Growth",2025-10-20 12:47:29+01:00,2025-10-20,2025-10-21,1359.000000
262,383069aae98a872604342c075637692b725b2b4ed57bbde8612541c67d6eb4b2,2025-11-06T13:02:40+00:00,https://www.sharecast.com/news/news-and-announcements/smith-nephew-q3-revenues-grow-raises-fcf-guidance--21172389.html,SN.L,Smith & Nephew plc,"Smith & Nephew Q3 revenues grow, raises FCF guidance",2025-11-06 13:02:40+00:00,2025-11-06,2025-11-07,1244.500000
263,dcd1919a7bbcf6d6f8a3cb1dd913bef6e963b1a7785bf8c41e4d963332a480fc,2025-11-13T12:17:33+00:00,https://www.proactiveinvestors.co.uk/companies/news/1082427/smith-nephew-steadies-expectations-as-investors-look-to-december-1082427.html,SN.L,Smith & Nephew plc,Smith & Nephew steadies expectations as investors look to December,2025-11-13 12:17:33+00:00,2025-11-13,2025-11-14,1248.000000
264,47c9d2131071583588870496734e193880dc5cf227d4c8f5f455ec23adbcb5a9,2025-11-20T13:03:19+00:00,https://www.tickerreport.com/banking-finance/13257222/saturna-capital-corp-invests-312000-in-smith-nephew-snats-inc-snn.html,SN.L,Smith & Nephew plc,"Saturna Capital Corp Invests $312,000 in Smith & Nephew SNATS, Inc. $SNN",2025-11-20 13:03:19+00:00,2025-11-20,2025-11-21,1226.000000
265,85d05d5d0bd24772171b66e1812e1a337046484db2c35ad6eb9e4816cc378faf,2025-12-04T12:32:27+00:00,https://www.themarketsdaily.com/2025/12/04/smith-nephew-lonsn-earns-outperform-rating-from-royal-bank-of-canada.html,SN.L,Smith & Nephew plc,"Smith & Nephew (LON:SN) Earns ""Outperform"" Rating from Royal Bank Of Canada",2025-12-04 12:32:27+00:00,2025-12-04,2025-12-05,1228.000000
266,6cae7b64b2b3c4bec3bdfad57228e7a91b7ad0c0384ac3499d53aef67e27c07d,2025-12-08T08:17:00+00:00,https://www.proactiveinvestors.co.uk/companies/news/1083943/smith-nephew-nudges-up-guidance-and-unveils-new-strategic-plan-1083943.html,SN.L,Smith & Nephew plc,Smith & Nephew nudges up guidance and unveils new strategic plan,2025-12-08 08:17:00+00:00,2025-12-08,2025-12-09,1248.000000
267,7c6145ca91afa1a307b1d754a5ff7e20a51cb26997cdc61faa9a1f6b061c2a62,2025-12-08T11:46:56+00:00,https://www.directorstalkinterviews.com/smith-nephew-outlines-rise-strategy-with-upgraded-guidance-and-new-2028-financial-targets/4121229411,SN.L,Smith & Nephew plc,Smith & Nephew Outlines RISE Strategy With Upgraded Guidance And New 2028 Financial Targets,2025-12-08 11:46:56+00:00,2025-12-08,2025-12-09,1248.000000
268,f9edbd6d2d6fbb74c271092ae413beaf1c3eaec97dff2f79099217f2d03a432a,2025-12-08T13:32:43+00:00,https://www.sharecast.com/news/news-and-announcements/smith-nephew-boosts-guidance-as-it-unveils-new-strategy--21340100.html,SN.L,Smith & Nephew plc,Smith & Nephew boosts guidance as it unveils new strategy,2025-12-08 13:32:43+00:00,2025-12-08,2025-12-09,1248.000000
269,aff13fbcbf4f1b2001be05cec907776bf08b06fdc66587e1ad4f3aa85cc074aa,2025-12-20T07:31:56+00:00,https://www.tickerreport.com/banking-finance/13296948/smith-nephew-lonsn-cut-to-sector-perform-at-royal-bank-of-canada.html,SN.L,Smith & Nephew plc,Smith & Nephew (LON:SN) Cut to Sector perform at Royal Bank Of Canada,2025-12-20 07:31:56+00:00,2025-12-20,2025-12-22,1229.000000

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
270,0c10bef6e3a6ce7cb2247d0555b8cb8ccc51fd72aff40f57fe321d5522a9ef9e,2025-01-16T01:01:41+00:00,https://www.dailypost.vu/news/vodafone-ath-fiji-foundation-pledges-over-vt1m-for-vanuatu-earthquake-relief/article_005fd339-0cbe-57fe-9f1e-358b89088f5a.html,VOD.L,Vodafone Group plc,Vodafone ATH Fiji Foundation pledges over VT1M for Vanuatu earthquake relief,2025-01-16 01:01:41+00:00,2025-01-16,2025-01-17,69.419998
271,92b626a92c37e00347d0bba53d572995597c011774a040754c420f3d92aa73a2,2025-01-17T15:47:32+00:00,https://www.marketscreener.com/quote/stock/HEPSIBURADA-124328863/news/D-MARKET-Electronic-Services-Trading-and-Vodafone-Turkiye-Join-Forces-to-Enhance-Customer-Experien-48800311/,VOD.L,Vodafone Group plc,D-MARKET Electronic Services & Trading and Vodafone Turkiye Join Forces to Enhance Customer Experience,2025-01-17 15:47:32+00:00,2025-01-17,2025-01-20,69.480003
272,8d6e40d2f2214b545eb5091d01332eda23da3b7de0ef0dee25cb05bbb30826f6,2025-02-18T10:16:53+00:00,https://metro.co.uk/2025/02/18/thousands-vodafone-customers-locked-mobile-banking-outage-22578349/,VOD.L,Vodafone Group plc,Vodafone app down with thousands of customers locked out of internet banking | News Tech,2025-02-18 10:16:53+00:00,2025-02-18,2025-02-19,65.760002
273,b57ae1cf7e7457ed5b6d31ae46f75e39800a66e3115d08d4c65919f1dac3addc,2025-02-25T08:16:48+00:00,https://www.manilatimes.net/2025/02/25/tmt-newswire/globenewswire/nokia-vodafone-and-ringcentral-to-showcase-future-of-voice-calls-at-mobile-world-congress-mwc25/2061827,VOD.L,Vodafone Group plc,"Nokia, Vodafone and RingCentral to showcase future of voice calls at Mobile World Congress #MWC25",2025-02-25 08:16:48+00:00,2025-02-25,2025-02-26,68.940002
274,4d21d347ec6fa69c9a3ae7983ddee82a0d84255f4cf769d789448c773c2390f5,2025-03-06T14:32:14+00:00,https://www.wkrb13.com/2025/03/06/midwest-heritage-bank-fsb-sells-7925-shares-of-vodafone-group-public-limited-nasdaqvod.html,VOD.L,Vodafone Group plc,"Midwest Heritage Bank FSB Sells 7,925 Shares of Vodafone Group Public Limited (NASDAQ:VOD)",2025-03-06 14:32:14+00:00,2025-03-06,2025-03-07,70.000000
275,4a6e15a4d7c7f95d77689ed8c521b3af44add603f0e1fc64c5f1fc2d931f08f2,2025-03-28T14:01:53+00:00,https://www.thediplomat.ro/2021/10/11/vodafone-supports-the-first-romanian-team-at-the-european-rocketry-challenge-competition-in-portugal/,VOD.L,Vodafone Group plc,Vodafone supports the first Romanian team at the European Rocketry Challenge competition in Portugal,2025-03-28 14:01:53+00:00,2025-03-28,2025-03-31,72.980003
276,a0d18ad4be6872901306843c798bd01a0db521d93b8425dd7d3c67bf701e04ba,2025-04-01T09:02:18+00:00,https://www.birminghammail.co.uk/news/midlands-news/vodafone-brings-new-rules-today-31323733,VOD.L,Vodafone Group plc,Vodafone brings in new rules from today and 'understands nobody will like them',2025-04-01 10:02:18+01:00,2025-04-01,2025-04-02,71.480003
277,c98966d7497e2eaa318b0f6ea293e025df0c4d341f28dc513640ed47476c9acf,2025-04-07T22:02:08+00:00,https://www.t3.com/tech/win-glastonbury-festival-2025-tickets-with-vodafone-rewards,VOD.L,Vodafone Group plc,No Glastonbury ticket? Vodafone offers customers chance to win,2025-04-07 23:02:08+01:00,2025-04-07,2025-04-08,65.239998
278,a8183f57898caec858b13da40e61d5712d43edfd35cb6081b9a6cfd88f5df67c,2025-04-08T04:01:53+00:00,https://www.thefastmode.com/mobile-network-operators-g-p/40847-vodafone-group-unifies-procurement-roaming-divisions-under-new-brand,VOD.L,Vodafone Group plc,"Vodafone Brings Roaming, Procurement Divisions Under One Umbrella",2025-04-08 05:01:53+01:00,2025-04-08,2025-04-09,64.199997
279,bf1c2ee1b42866410798589e62ca692e079d2f1195b8b2b10036404d6694b79b,2025-04-15T04:16:50+00:00,https://www.cookislandsnews.com/internal/national/business/vodafone-launches-new-retail-store/,VOD.L,Vodafone Group plc,Vodafone launches new retail store - Cook Islands News,2025-04-15 05:16:50+01:00,2025-04-15,2025-04-16,69.180000
280,6fceb1e3fae004cea60606f719257bc23aec4ad18707800f943b93963bb615da,2025-04-23T09:31:59+00:00,https://actmedia.eu/companies/competition-council-voices-concerns-over-vodafone-digi-s-intention-to-take-over-telekom/113620,VOD.L,Vodafone Group plc,"Competition Council voices concerns over Vodafone, Digi's intention to take over Telekom",2025-04-23 10:31:59+01:00,2025-04-23,2025-04-24,70.019997
281,e661696f7e03d3247cc6b86d401738ef32d767753a5791341169a77c6f56e33a,2025-04-27T08:01:40+00:00,https://www.theguardian.com/business/2025/apr/27/vodafone-whistleblowers-warned-executives-about-plight-of-high-street-store-staff,VOD.L,Vodafone Group plc,Vodafone whistleblowers warned executives about plight of high street store staff,2025-04-27 09:01:40+01:00,2025-04-27,2025-04-28,70.660004
282,8c475d20d3806be44c3a53348565c09b224871faea491d3732e909ae86a0bc24,2025-05-20T14:46:50+00:00,https://www.birminghammail.co.uk/news/money/talks-end-vodafone-120-million-31684464,VOD.L,Vodafone Group plc,Talks to end Vodafone £120 million legal claim fail,2025-05-20 15:46:50+01:00,2025-05-20,2025-05-21,77.760002
283,6461d657d25d7de195b08f07270126b213f6bcd48b2c74c3016c44696b8c80a0,2025-05-23T12:32:55+00:00,https://www.redfm.ie/national/vodafones-a-strangers-tale-podcast-series-shows-the-power-of-connection-2164878,VOD.L,Vodafone Group plc,Vodafone's A Stranger's Tale Podcast Series Shows The Power of Connection,2025-05-23 13:32:55+01:00,2025-05-23,2025-05-27,77.360001
284,cf40eac4ed2241e6c6b659fd3bc0dc19cac04d68d0c05751dec7e35ad1b8ede7,2025-05-26T01:02:02+00:00,https://www.itnews.com.au/news/telstra-addresses-external-antenna-claims-by-vodafone-617415,VOD.L,Vodafone Group plc,Telstra addresses external antenna claims by Vodafone,2025-05-26 02:02:02+01:00,2025-05-26,2025-05-27,77.360001
285,790920ae55439dbdc323022e23353355a35a4fcdfcc46be3a33bee938600c50d,2025-05-27T20:17:25+00:00,https://www.kachwanya.com/2016/03/01/vodafone-introduces-instant-classroom-lite-platforms-for-refugee-camps/,VOD.L,Vodafone Group plc,Vodafone introduces instant Classroom lite platforms for refugee camps,2025-05-27 21:17:25+01:00,2025-05-27,2025-05-28,77.900002
286,c2dfe158880021975727acf7fba05ce5f5a6f7dc1c58bb0b9d0f4be9af1c4c61,2025-06-03T11:01:54+00:00,https://www.computerweekly.com/news/366625234/Vodafone-Three-UK-complete-UK-merger,VOD.L,Vodafone Group plc,"Vodafone, Three UK complete UK merger | Computer Weekly",2025-06-03 12:01:54+01:00,2025-06-03,2025-06-04,76.040001
287,d39a89e8b8feaf177ce898910b98b6d2079b0dea46026df6fd680832b5d681f7,2025-06-05T12:02:44+00:00,https://www.ispreview.co.uk/index.php/2025/06/vodafone-uk-launches-new-5g-mobile-data-travel-esim-service.html,VOD.L,Vodafone Group plc,Vodafone UK Launches New 5G Mobile Data Travel eSIM Service,2025-06-05 13:02:44+01:00,2025-06-05,2025-06-06,73.720001
288,486b3befea974af0e910a42aa5ff4c6ba02b9d499a9c9a885959b3e6642ef3c9,2025-09-19T15:32:22+00:00,https://www.romaniapress.com/news=187147,VOD.L,Vodafone Group plc,"Romania: Vodafone, Digi acquire Telekom Romania assets in EUR 70 mln deal",2025-09-19 16:32:22+01:00,2025-09-19,2025-09-22,84.839996
289,373e3552f1db74f4d6cecd73f0583e2de0bcd46cffbfc68d6b6d15efba9b1f32,2025-10-01T22:32:03+00:00,https://www.romaniapress.com/news=187467,VOD.L,Vodafone Group plc,Romania: Vodafone And Digi Announce Completion Of Telekom Romania Mobile (…),2025-10-01 23:32:03+01:00,2025-10-01,2025-10-02,85.779999
290,30d0a3dfe452f963a4accc2bfcb5e02223461d4c25c6d65496f684d0ebbe99ba,2025-10-10T01:17:08+00:00,https://www.bandt.com.au/vodafone-gets-weird-in-new-iphone-spruiking-campaign-via-thinkerbell/,VOD.L,Vodafone Group plc,Vodafone Gets Weird In New iPhone-Spruiking Campaign Via Thinkerbell,2025-10-10 02:17:08+01:00,2025-10-10,2025-10-13,85.199997
291,f3f4668340925159473eae0068fca4b3cf8aa83ee7085caa19ad08d9f9327622,2025-10-13T19:17:29+00:00,https://www.mirror.co.uk/news/uk-news/vodafone-broadband-users-issue-compensation-36062574,VOD.L,Vodafone Group plc,Vodafone broadband users compensation demand as full statement issued,2025-10-13 20:17:29+01:00,2025-10-13,2025-10-14,83.519997
292,b7766e3ceb2481d014f5635fc03627e9226309f4613a1c3626edd3cb2665e568,2025-10-28T17:47:36+00:00,https://www.asianage.com/opinion/edit/aa-edit-vodafone-relief-raises-questions-1913208,VOD.L,Vodafone Group plc,AA Edit | Vodafone Relief Raises Questions,2025-10-28 17:47:36+00:00,2025-10-28,2025-10-29,92.620003
293,da86d4a139e28d9000e5116623dcf6003e33c2458ebdad7bceccb50dd6d641f6,2025-10-29T05:47:12+00:00,https://telecom.economictimes.indiatimes.com/news/industry/european-telecom-giants-demand-looser-merger-rules-to-compete-globally/124887785,VOD.L,Vodafone Group plc,"Vodafone: European Telecom Giants Demand Looser Merger Rules to Compete Globally, ETTelecom",2025-10-29 05:47:12+00:00,2025-10-29,2025-10-30,91.139999
294,d68ee1a91a2d375b01fbccbbab415b261b17059cd13165449c2600aac5925503,2025-10-30T07:16:49+00:00,https://www.investegate.co.uk/announcement/rns/vodafone-group--vod/vodafone-to-acquire-skaylink/9202807,VOD.L,Vodafone Group plc,Vodafone to acquire Skaylink | Company Announcement,2025-10-30 07:16:49+00:00,2025-10-30,2025-10-31,91.199997
295,32e4957c8eddd53a1ce183cb2412a53c83b10664f33170ffc3e58365fdb6396e,2025-11-06T19:01:59+00:00,https://techgadgetcentral.com/2023/10/11/uk-antitrust-regulator-investigates-19b-vodafonethree-mobile-merger/,VOD.L,Vodafone Group plc,UK antitrust regulator investigates $19B Vodafone/Three mobile merger,2025-11-06 19:01:59+00:00,2025-11-06,2025-11-07,86.959999
296,4820efbe52d438c9988978fdf6d050d99d03719ca33983068753c0280c55f2c8,2025-11-07T09:16:58+00:00,https://telecom.economictimes.indiatimes.com/news/portal-in-portal/satcom/vodafone-and-ast-spacemobile-launch-europes-first-satellite-constellation-for-smartphone-connectivity/125155290,VOD.L,Vodafone Group plc,"Vodafone and AST SpaceMobile Launch Europe's First Satellite Constellation for Smartphone Connectivity, ETTelecom",2025-11-07 09:16:58+00:00,2025-11-07,2025-11-10,87.519997
297,e247997ebc1ee9d6782752a0a3a2f58d2292a27e4d3f69a762cd82eb7ef11cf9,2025-11-10T14:17:33+00:00,https://www.thefastmode.com/technology-solutions/45759-vodafone-launches-ai-driven-field-technician-assist-powered-by-celfocus,VOD.L,Vodafone Group plc,"Vodafone Launches AI-Driven Field Technician Assist, Powered by Celfocus",2025-11-10 14:17:33+00:00,2025-11-10,2025-11-11,93.239998
298,ee07883ed75630181aa82892688c66abb4b505a1bcb136165fdbebf6648d62b1,2025-11-18T10:47:41+00:00,https://www.theregister.com/2025/11/18/uk_mobile_overcharging_suit/,VOD.L,Vodafone Group plc,"Vodafone, EE, O2, Three hit with £3B overcharging lawsuit",2025-11-18 10:47:41+00:00,2025-11-18,2025-11-19,92.919998
299,c5fc6610a8677e449f36c064a7db4c7eccaf6e0309e7cf4ea519e42427f0b4ab,2025-12-17T16:32:34+00:00,https://www.telecomtv.com/content/access-evolution/what-s-up-with-telef-nica-liberty-global-vodafone-54548/,VOD.L,Vodafone Group plc,"What's up with… Telefónica, Liberty Global, Vodafone, Access Evolution",2025-12-17 16:32:34+00:00,2025-12-17,2025-12-18,95.940002

In [168]:
# After investigating the samples above, it was found that the indices 1, 143 and 163 are duplicates of indices 0, 142 and 162 respectively. Therefore, they are replaced replaced with alternate headlines from the `headlines_aligned_prices.csv` for the same company ticker to eliminate any duplications. 
duplicate_replacements = {
    1: (
        "3d7dfe781decf4fc0114ae2198c293fd56e90d7676b91e46f7e444872358920d",
        "b5fea3607bcfdf442b99b9975d611804dcb7faeb95ee472def5b9ac095a7bb1d",
    ),
    143: (
        "a6d2872810ea241f7df20cb4bee1039a48a5cbb9bc6d19aaaffcbfdb6d803a94",
        "160526a9b5332786c0bb64ce308c483fa9ceaec05eb5d9f6da5f817ce0deb192",
    ),
    163: (
        "38dc6600edaedb80c9b7919cb52d914f74646efe40b4be699be8ed50380475c1",
        "cb1a4838296bbdcdda312669fc261cd71e5d2a3a9a4c1102a69922dcd251f025",
    ),
}

for row_number, (duplicate_id, replacement_id) in duplicate_replacements.items():
    replacement = headlines_aligned_prices_df.loc[headlines_aligned_prices_df[HEADLINE_ID_COLUMN] == replacement_id]

    sample_df.loc[row_number] = replacement.iloc[0][sample_df.columns]

display(sample_df)

,headline_id,published_at_utc,url,ticker,company_name,headline_text,published_at_london,headline_date_london,trade_date,trade_open
0,5ede6243dbcfa061b21ac3df0436800d494f62bac455d88689a9493ed3a2f92a,2025-01-21T06:16:32+00:00,https://www.tmcnet.com/usubmit/2025/01/21/10133722.htm,AZN.L,AstraZeneca plc,Trinasolar Powers AstraZeneca's Sustainability Vision with Cutting-Edge Solar Carpark Rooftop Install,2025-01-21 06:16:32+00:00,2025-01-21,2025-01-22,11010.000000
1,b5fea3607bcfdf442b99b9975d611804dcb7faeb95ee472def5b9ac095a7bb1d,2025-03-17T10:17:13+00:00,https://www.theguardian.com/business/2025/mar/17/astrazeneca-biotech-cancer-cell-therapy-esobiotec-imfinzi,AZN.L,AstraZeneca plc,AstraZeneca pays up to $1bn for biotech firm 'that could transform cell therapy' | AstraZeneca,2025-03-17 10:17:13+00:00,2025-03-17,2025-03-18,11908.000000
2,5fe27a5b2aed7baf82841ba8630de456922c1667363ee4b2ea7887bf3ed56052,2025-01-22T13:47:57+00:00,https://www.pharmiweb.com/press-release/2025-01-22/astrazeneca-receives-two-positive-nice-recommendations-for-lung-cancer-patients-across-england-and-wales,AZN.L,AstraZeneca plc,ASTRAZENECA RECEIVES TWO POSITIVE NICE RECOMMENDATIONS FOR LUNG CANCER PATIENTS ACROSS ENGLAND AND WALES,2025-01-22 13:47:57+00:00,2025-01-22,2025-01-23,11098.000000
3,56043810e5296999170979275395f9d41861a4f5ae08c5787cf4a4879254928d,2025-02-01T19:32:28+00:00,https://www.thetimes.com/business-money/companies/article/astrazeneca-accused-of-rowing-back-on-pledges-in-vaccine-hub-row-cbqqpp2nx,AZN.L,AstraZeneca plc,AstraZeneca accused of rowing back on pledges in vaccine hub row,2025-02-01 19:32:28+00:00,2025-02-01,2025-02-03,11248.000000
4,f9306acc0e15bdb3ff36576665abac854f1f09f1049f29f66441bcb49355e4f3,2025-02-01T20:16:32+00:00,https://www.dailymail.co.uk/news/article-14350315/Covid-Labour-AstraZeneca-vaccine-site.html,AZN.L,AstraZeneca plc,Covid chief attacks Labour after AstraZeneca axes its plan for £450million vaccine site,2025-02-01 20:16:32+00:00,2025-02-01,2025-02-03,11248.000000
...,...,...,...,...,...,...,...,...,...,...
295,32e4957c8eddd53a1ce183cb2412a53c83b10664f33170ffc3e58365fdb6396e,2025-11-06T19:01:59+00:00,https://techgadgetcentral.com/2023/10/11/uk-antitrust-regulator-investigates-19b-vodafonethree-mobile-merger/,VOD.L,Vodafone Group plc,UK antitrust regulator investigates $19B Vodafone/Three mobile merger,2025-11-06 19:01:59+00:00,2025-11-06,2025-11-07,86.959999
296,4820efbe52d438c9988978fdf6d050d99d03719ca33983068753c0280c55f2c8,2025-11-07T09:16:58+00:00,https://telecom.economictimes.indiatimes.com/news/portal-in-portal/satcom/vodafone-and-ast-spacemobile-launch-europes-first-satellite-constellation-for-smartphone-connectivity/125155290,VOD.L,Vodafone Group plc,"Vodafone and AST SpaceMobile Launch Europe's First Satellite Constellation for Smartphone Connectivity, ETTelecom",2025-11-07 09:16:58+00:00,2025-11-07,2025-11-10,87.519997
297,e247997ebc1ee9d6782752a0a3a2f58d2292a27e4d3f69a762cd82eb7ef11cf9,2025-11-10T14:17:33+00:00,https://www.thefastmode.com/technology-solutions/45759-vodafone-launches-ai-driven-field-technician-assist-powered-by-celfocus,VOD.L,Vodafone Group plc,"Vodafone Launches AI-Driven Field Technician Assist, Powered by Celfocus",2025-11-10 14:17:33+00:00,2025-11-10,2025-11-11,93.239998
298,ee07883ed75630181aa82892688c66abb4b505a1bcb136165fdbebf6648d62b1,2025-11-18T10:47:41+00:00,https://www.theregister.com/2025/11/18/uk_mobile_overcharging_suit/,VOD.L,Vodafone Group plc,"Vodafone, EE, O2, Three hit with £3B overcharging lawsuit",2025-11-18 10:47:41+00:00,2025-11-18,2025-11-19,92.919998
299,c5fc6610a8677e449f36c064a7db4c7eccaf6e0309e7cf4ea519e42427f0b4ab,2025-12-17T16:32:34+00:00,https://www.telecomtv.com/content/access-evolution/what-s-up-with-telef-nica-liberty-global-vodafone-54548/,VOD.L,Vodafone Group plc,"What's up with… Telefónica, Liberty Global, Vodafone, Access Evolution",2025-12-17 16:32:34+00:00,2025-12-17,2025-12-18,95.940002

## Labelling guide

In this section, the labels will be assigned according to the likely financial effect on the respective company based solely on the headline. 

- **positive**: a clearly favourable development, such as improved results, an approval, a contract win, or an upgrade.
- **negative**: a clearly unfavourable development, such as weaker results, a warning, disruption, or a downgrade.
- **neutral**: an unclear positive or negative effect.

This headline-only, entity-aware approach is supported by [Sinha et al. (2022)](https://doi.org/10.1002/asi.24634).

The labelling method was adapted from the entity-aware approach of Sinha et al. (2022)(https://doi.org/10.1002/asi.24634). Each headline was classified as positive, negative or neutral specifically in relation to the named company. Labels were based only on information explicitly stated in the headline, without using later share-price movements, article content or prior knowledge.

As for the `label_gold`, this is the term widely used for labels manually done by humans as per the following source ["Data manually labeled by human beings is often referred to as gold labels"](https://developers.google.com/machine-learning/crash-course/categorical-data/issues)

In [ ]:
labelling_relevant_columns = [
    HEADLINE_ID_COLUMN,
    TICKER_COLUMN,
    COMPANY_NAME_COLUMN,
    PUBLISHED_AT_LONDON_COLUMN,
    HEADLINE_TEXT_COLUMN,
]

# Copy the relevant columns from the `sample_df` to a new `manual_sentiment_labelled_df`
manual_sentiment_labelled_df = sample_df[labelling_relevant_columns].copy()
# Create a new column called "label_gold" to populate in the subsequent notebook code blocks
manual_sentiment_labelled_df[LABEL_GOLD_COLUMN] = ""

def assign_labels(indices, label):
    """Assign one final sentiment label to the specified sample rows."""

    # Ensure that the label passed into the definition is a valid value of the VALID_SENTIMENT_LABELS set
    assert label in VALID_SENTIMENT_LABELS
    # Ensure that not index is assigned a label twice by mistake
    assert manual_sentiment_labelled_df.loc[indices, LABEL_GOLD_COLUMN].eq("").all()

    manual_sentiment_labelled_df.loc[indices, LABEL_GOLD_COLUMN] = label

#### The following lines of code are to assign the appropriate labels (`POSITIVE_LABEL, NEGATIVE_LABEL, NEUTRAL_LABEL`) to their respective row based on the manual review of 30 rows for each company

In [170]:
# AstraZeneca (AZN.L): rows 0-29
assign_labels([0, 1, 2, 6, 9, 16, 17, 18, 19, 23, 25, 27], POSITIVE_LABEL)
assign_labels([3, 4, 7, 8, 15, 24], NEGATIVE_LABEL)
assign_labels([5, 10, 11, 12, 13, 14, 20, 21, 22, 26, 28, 29], NEUTRAL_LABEL)

In [171]:
# GSK (GSK.L): rows 30-59
assign_labels(
    [31, 33, 34, 35, 36, 38, 41, 43, 44, 45, 46, 47, 50, 52, 56, 57],
    POSITIVE_LABEL,
)
assign_labels([39, 40, 42, 49], NEGATIVE_LABEL)
assign_labels([30, 32, 37, 48, 51, 53, 54, 55, 58, 59], NEUTRAL_LABEL)

In [172]:
# Halma (HLMA.L): rows 60-89
assign_labels(
    [64, 65, 66, 67, 68, 69, 70, 72, 73, 74, 75, 76, 77, 79, 80, 81, 82, 83, 84, 88],
    POSITIVE_LABEL,
)
assign_labels([62, 78, 85], NEGATIVE_LABEL)
assign_labels([60, 61, 63, 71, 86, 87, 89], NEUTRAL_LABEL)

In [173]:
# HSBC (HSBA.L): rows 90-119
assign_labels([90, 92, 93, 96, 97, 100, 103, 111, 113, 114, 115], POSITIVE_LABEL)
assign_labels([94, 95, 99, 102, 109], NEGATIVE_LABEL)
assign_labels(
    [91, 98, 101, 104, 105, 106, 107, 108, 110, 112, 116, 117, 118, 119],
    NEUTRAL_LABEL,
)

In [174]:
# Intertek (ITRK.L): rows 120-149
assign_labels(
    [120, 121, 122, 123, 124, 125, 126, 130, 132, 133, 135, 136, 137, 141, 142, 145, 146, 147, 148],
    POSITIVE_LABEL,
)
assign_labels([128, 129, 134, 140, 144], NEGATIVE_LABEL)
assign_labels([127, 131, 138, 139, 143, 149], NEUTRAL_LABEL)

In [175]:
# National Grid (NG.L): rows 150-179
assign_labels([155, 162, 165, 170, 171, 173, 176, 177, 179], POSITIVE_LABEL)
assign_labels([150, 152, 153, 157, 158, 159, 164, 166, 167, 172, 178], NEGATIVE_LABEL)
assign_labels([151, 154, 156, 160, 161, 163, 168, 169, 174, 175], NEUTRAL_LABEL)

In [176]:
# RELX (REL.L): rows 180-209
assign_labels(
    [180, 181, 182, 183, 184, 187, 189, 190, 191, 192, 194, 195, 196, 201, 202, 203, 204, 206, 207, 208],
    POSITIVE_LABEL,
)
assign_labels([185, 186, 193, 197, 209], NEGATIVE_LABEL)
assign_labels([188, 198, 199, 200, 205], NEUTRAL_LABEL)

In [177]:
# Rio Tinto (RIO.L): rows 210-239
assign_labels([215, 216, 219, 220, 221, 225, 227, 230, 232, 233, 237], POSITIVE_LABEL)
assign_labels([210, 217, 218, 223, 224, 226, 228, 236], NEGATIVE_LABEL)
assign_labels([211, 212, 213, 214, 222, 229, 231, 234, 235, 238, 239], NEUTRAL_LABEL)

In [178]:
# Smith & Nephew (SN.L): rows 240-269
assign_labels(
    [240, 241, 242, 243, 244, 246, 247, 248, 253, 259, 260, 261, 262, 264, 265, 266, 267, 268],
    POSITIVE_LABEL,
)
assign_labels([249, 252, 254, 269], NEGATIVE_LABEL)
assign_labels([245, 250, 251, 255, 256, 257, 258, 263], NEUTRAL_LABEL)

In [179]:
# Vodafone (VOD.L): rows 270-299
assign_labels([271, 273, 275, 283, 285, 286, 287, 288, 289, 294, 296, 297], POSITIVE_LABEL)
assign_labels([272, 274, 276, 280, 281, 282, 291, 292, 295, 298], NEGATIVE_LABEL)
assign_labels([270, 277, 278, 279, 284, 290, 293, 299], NEUTRAL_LABEL)

In [180]:
# Confirm that exactly 300 headlines were selected for manual labelling
assert len(manual_sentiment_labelled_df) == 300 # 300 because index 0 - 299
# Confirm that each company contributes the required number of headlines
assert manual_sentiment_labelled_df.groupby(TICKER_COLUMN).size().eq(SAMPLE_PER_COMPANY).all()
# Confirm that no sampled headline was left without a label
assert not manual_sentiment_labelled_df[LABEL_GOLD_COLUMN].eq("").any()

# Keep only the columns required for the final gold-label dataset.
gold_columns = [HEADLINE_ID_COLUMN, LABEL_GOLD_COLUMN]
gold_labels_df = manual_sentiment_labelled_df[gold_columns].copy()

# Create the output directory if needed and save the final labels.
gold_labels_path.parent.mkdir(parents=True, exist_ok=True)
gold_labels_df.to_csv(gold_labels_path, index=False)

# Display the number of headlines assigned to each sentiment class.
display(gold_labels_df[LABEL_GOLD_COLUMN].value_counts())
# Report how many labels were saved and where the file was written to.
print(f"Saved {len(gold_labels_df)} final labels to {gold_labels_path}")

label_gold
positive    148
neutral      91
negative     61
Name: count, dtype: int64

Saved 300 final labels to c:\Users\PC\Desktop\Masters\09 Capstone Project - Dissertation\Week 40\DK-CoT_UK_Stocks\data\processed\gold_labels.csv